; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s --check-prefix=CHECK16
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 < %s | FileCheck %s --check-prefix=CHECK32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s --check-prefix=CHECK64

;; ===========================================================================
;; ETCA G_ANYEXT test — i16 zext i1 (valid on all word size targets)
;;
;; G_ICMP produces a 16-bit condition value.  When the consumer expects a
;; wider type (e.g., G_AND with a 1 mask on a wider result), the legalizer
;; inserts G_ANYEXT to bridge the width mismatch.  G_ANYEXT must be handled
;; in the instruction selector as a simple COPY (high bits are undefined).
;;
;; On 16-bit targets the i16 return is in a 16-bit register, so no G_ANYEXT
;; On wider targets the i16 return is in a wider register (d0/q0)
;; which triggers G_ANYEXT from s16 → s32/s64.
;; ===========================================================================

define i16 @zext_i1_to_i16(i16 %x) {
; CHECK16-LABEL: zext_i1_to_i16:
; CHECK16:       movz %r1, 0
; CHECK16-NEXT:  cmp %r0, %r1
; CHECK16-NEXT:  bne .LBB0_1
; CHECK16-NEXT:  br .LBB0_2
; CHECK16-NEXT: .LBB0_1:
; CHECK16-NEXT:  movz %r0, 0
; CHECK16-NEXT:  br .LBB0_3
; CHECK16-NEXT: .LBB0_2:
; CHECK16-NEXT:  movz %r0, 1
; CHECK16-NEXT: .LBB0_3:
; CHECK16-NEXT:  jmpr %r7
;
; CHECK32-LABEL: zext_i1_to_i16:
; CHECK32:       movz %r1, 0
; CHECK32-NEXT:  cmp %r0, %r1
; CHECK32-NEXT:  bne .LBB0_1
; CHECK32-NEXT:  br .LBB0_2
; CHECK32-NEXT: .LBB0_1:
; CHECK32-NEXT:  movz %r0, 0
; CHECK32-NEXT:  br .LBB0_3
; CHECK32-NEXT: .LBB0_2:
; CHECK32-NEXT:  movz %r0, 1
; CHECK32-NEXT: .LBB0_3:
; CHECK32-NEXT:  movz %r1d, %r0
; CHECK32-NEXT:  movz %r0d, 1
; CHECK32-NEXT:  and %r0d, %r1d
; CHECK32-NEXT:  jmpr %r7
;
; CHECK64-LABEL: zext_i1_to_i16:
; CHECK64:       movz %r1, 0
; CHECK64-NEXT:  cmp %r0, %r1
; CHECK64-NEXT:  bne .LBB0_1
; CHECK64-NEXT:  br .LBB0_2
; CHECK64-NEXT: .LBB0_1:
; CHECK64-NEXT:  movz %r0, 0
; CHECK64-NEXT:  br .LBB0_3
; CHECK64-NEXT: .LBB0_2:
; CHECK64-NEXT:  movz %r0, 1
; CHECK64-NEXT: .LBB0_3:
; CHECK64-NEXT:  movz %r1q, %r0
; CHECK64-NEXT:  movz %r0q, 1
; CHECK64-NEXT:  and %r0q, %r1q
; CHECK64-NEXT:  jmpr %r7
  %cmp = icmp eq i16 %x, 0
  %conv = zext i1 %cmp to i16
  ret i16 %conv
}
