; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 < %s | FileCheck %s --check-prefix=CHECK32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s --check-prefix=CHECK64

;; ===========================================================================
;; ETCA G_ANYEXT test — i32 zext i1 (valid on 32-bit and 64-bit targets)
;;
;; On 16-bit targets i32 is split into two 16-bit halves (G_MERGE_VALUES,
;; unsupported), so this test is excluded from 16-bit runs.
;;
;; G_ICMP produces a 16-bit condition value.  When the consumer expects a
;; wider type (32 or 64 bits), the legalizer inserts G_ANYEXT to bridge the
;; width mismatch.  G_ANYEXT must be handled in the instruction selector as
;; a simple COPY (high bits are undefined).
;; ===========================================================================

define i32 @zext_i1_to_i32(i32 %x) {
; CHECK32-LABEL: zext_i1_to_i32:
; CHECK32:      movz %r1d, 0
; CHECK32-NEXT: cmp %r0d, %r1d
; CHECK32-NEXT: bne .LBB0_1
; CHECK32-NEXT: br .LBB0_2
; CHECK32-NEXT: .LBB0_1:
; CHECK32-NEXT: movz %r0, 0
; CHECK32-NEXT: br .LBB0_3
; CHECK32-NEXT: .LBB0_2:
; CHECK32-NEXT: movz %r0, 1
; CHECK32-NEXT: .LBB0_3:
; CHECK32-NEXT: movz %r1d, %r0
; CHECK32-NEXT: movz %r0d, 1
; CHECK32-NEXT: and %r0d, %r1d
; CHECK32-NEXT: jmpr %r7
;
; CHECK64-LABEL: zext_i1_to_i32:
; CHECK64:      movz %r1d, 0
; CHECK64-NEXT: cmp %r0d, %r1d
; CHECK64-NEXT: bne .LBB0_1
; CHECK64-NEXT: br .LBB0_2
; CHECK64-NEXT: .LBB0_1:
; CHECK64-NEXT: movz %r0, 0
; CHECK64-NEXT: br .LBB0_3
; CHECK64-NEXT: .LBB0_2:
; CHECK64-NEXT: movz %r0, 1
; CHECK64-NEXT: .LBB0_3:
; CHECK64-NEXT: movz %r1q, %r0
; CHECK64-NEXT: movz %r0q, 1
; CHECK64-NEXT: and %r0q, %r1q
; CHECK64-NEXT: jmpr %r7
  %cmp = icmp eq i32 %x, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}
