; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s --check-prefix=CHECK64

;; ===========================================================================
;; ETCA G_ANYEXT test — i64 zext i1 (valid on 64-bit target only)
;;
;; On 16-bit and 32-bit targets i64 is split into narrower halves
;; (G_MERGE_VALUES, unsupported), so this test is excluded from those runs.
;;
;; G_ICMP produces a 16-bit condition value.  When the consumer expects a
;; wider type (64 bits), the legalizer inserts G_ANYEXT to bridge the width
;; mismatch.  G_ANYEXT must be handled in the instruction selector as a
;; simple COPY (high bits are undefined).
;; ===========================================================================

define i64 @zext_i1_to_i64(i64 %x) {
; CHECK64-LABEL: zext_i1_to_i64:
; CHECK64:      movz %r1q, 0
; CHECK64-NEXT: cmp %r0q, %r1q
; CHECK64-NEXT: bne .LBB0_1
; CHECK64-NEXT: br .LBB0_2
; CHECK64-NEXT: .LBB0_1:
; CHECK64-NEXT: movz %r0, 0
; CHECK64-NEXT: br .LBB0_3
; CHECK64-NEXT: .LBB0_2:
; CHECK64-NEXT: movz %r0, 1
; CHECK64-NEXT: .LBB0_3:
; CHECK64-NEXT: movz %r1q, %r0
; CHECK64-NEXT: movz %r0q, 1
; CHECK64-NEXT: and %r0q, %r1q
; CHECK64-NEXT: jmpr %r7
  %cmp = icmp eq i64 %x, 0
  %conv = zext i1 %cmp to i64
  ret i64 %conv
}
