; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s

;; ===========================================================================
;; ETCA arithmetic codegen tests — base 16-bit word + 16-bit pointer
;;
;; Tests all base arithmetic instructions in both register-register (RR) and
;; register-immediate (RI) forms.  The ETCA backend is a two-address 16-bit
;; ISA with 8 general-purpose registers (r0-r7).  First four i16 args arrive
;; in r0-r3 and the return value is in r0.  Register names use binutus syntax:
;; %rN for 16-bit, %rNd for 32-bit, %rNq for 64-bit.
;;
;; Covered:
;;   ADD / ADDI, SUB / SUBI, RSUB / RSUBI,
;;   OR  / ORI,  XOR / XORI, AND / ANDI,
;;   SLO (shift left), no-op optimisations.
;; ===========================================================================

;; --- ADD (register-register) ---

define i16 @add_rr(i16 %a, i16 %b) {
; CHECK-LABEL: add_rr:
; CHECK:       add %r0, %r1
; CHECK:       jmpr %r7
  %r = add i16 %a, %b
  ret i16 %r
}

;; --- ADD with small immediate (fits in 5-bit signed) ---

define i16 @add_ri_small(i16 %a) {
; CHECK-LABEL: add_ri_small:
; CHECK:       movz %r1, 10
; CHECK:       add %r0, %r1
; CHECK:       jmpr %r7
  %r = add i16 %a, 10
  ret i16 %r
}

define i16 @add_ri_zero(i16 %a) {
; CHECK-LABEL: add_ri_zero:
; CHECK:       jmpr %r7
  %r = add i16 %a, 0
  ret i16 %r
}

define i16 @add_ri_large(i16 %a) {
; CHECK-LABEL: add_ri_large:
; CHECK:       movz %r1, 31
; CHECK:       slo %r1, 8
; CHECK:       add %r0, %r1
; CHECK:       jmpr %r7
  %r = add i16 %a, 1000
  ret i16 %r
}

;; --- SUB (register-register) ---

define i16 @sub_rr(i16 %a, i16 %b) {
; CHECK-LABEL: sub_rr:
; CHECK:       sub %r0, %r1
; CHECK:       jmpr %r7
  %r = sub i16 %a, %b
  ret i16 %r
}

define i16 @sub_ri_small(i16 %a) {
; CHECK-LABEL: sub_ri_small:
; CHECK:       movz %r1, 1
; CHECK:       sub %r0, %r1
; CHECK:       jmpr %r7
  %r = sub i16 %a, 1
  ret i16 %r
}

define i16 @rsub_rr(i16 %a, i16 %b) {
; CHECK-LABEL: rsub_rr:
; CHECK:       sub %r0, %r1
; CHECK:       jmpr %r7
  %r = sub i16 %b, %a
  ret i16 %r
}

;; --- OR (register-register) ---

define i16 @or_rr(i16 %a, i16 %b) {
; CHECK-LABEL: or_rr:
; CHECK:       or %r0, %r1
; CHECK:       jmpr %r7
  %r = or i16 %a, %b
  ret i16 %r
}

define i16 @or_ri_small(i16 %a) {
; CHECK-LABEL: or_ri_small:
; CHECK:       movz %r1, 1
; CHECK:       or %r0, %r1
; CHECK:       jmpr %r7
  %r = or i16 %a, 1
  ret i16 %r
}

;; --- XOR (register-register) ---

define i16 @xor_rr(i16 %a, i16 %b) {
; CHECK-LABEL: xor_rr:
; CHECK:       xor %r0, %r1
; CHECK:       jmpr %r7
  %r = xor i16 %a, %b
  ret i16 %r
}

define i16 @xor_ri_small(i16 %a) {
; CHECK-LABEL: xor_ri_small:
; CHECK:       movz %r1, 15
; CHECK:       xor %r0, %r1
; CHECK:       jmpr %r7
  %r = xor i16 %a, 15
  ret i16 %r
}

;; --- AND (register-register) ---

define i16 @and_rr(i16 %a, i16 %b) {
; CHECK-LABEL: and_rr:
; CHECK:       and %r0, %r1
; CHECK:       jmpr %r7
  %r = and i16 %a, %b
  ret i16 %r
}

define i16 @and_ri_small(i16 %a) {
; CHECK-LABEL: and_ri_small:
; CHECK:       movz %r1, 15
; CHECK:       and %r0, %r1
; CHECK:       jmpr %r7
  %r = and i16 %a, 15
  ret i16 %r
}

;; --- SLO (shift left) ---

define i16 @shift_left(i16 %a) {
; CHECK-LABEL: shift_left:
; CHECK:       movz %r0, %r0
; CHECK:       add %r0, %r0
; CHECK:       add %r0, %r0
; CHECK:       jmpr %r7
  %r = shl i16 %a, 2
  ret i16 %r
}

define i16 @shift_left_by_zero(i16 %a) {
; CHECK-LABEL: shift_left_by_zero:
; CHECK:       movz %r0, %r0
; CHECK:       jmpr %r7
  %r = shl i16 %a, 0
  ret i16 %r
}

define i16 @shift_left_by_one(i16 %a) {
; CHECK-LABEL: shift_left_by_one:
; CHECK:       movz %r0, %r0
; CHECK:       add %r0, %r0
; CHECK:       jmpr %r7
  %r = shl i16 %a, 1
  ret i16 %r
}

;; --- Commutative patterns ---

define i16 @add_commuted(i16 %a, i16 %b) {
; CHECK-LABEL: add_commuted:
; CHECK:       add %r0, %r1
; CHECK:       jmpr %r7
  %r = add i16 %b, %a
  ret i16 %r
}

define i16 @or_commuted(i16 %a, i16 %b) {
; CHECK-LABEL: or_commuted:
; CHECK:       or %r0, %r1
; CHECK:       jmpr %r7
  %r = or i16 %b, %a
  ret i16 %r
}

;; --- Chained arithmetic ---

define i16 @chained_add_sub(i16 %x, i16 %y, i16 %z) {
; CHECK-LABEL: chained_add_sub:
; CHECK:       add %r0, %r1
; CHECK:       sub %r0, %r2
; CHECK:       jmpr %r7
  %sum = add i16 %x, %y
  %res = sub i16 %sum, %z
  ret i16 %res
}

define i16 @three_op_expression(i16 %a, i16 %b, i16 %c) {
; CHECK-LABEL: three_op_expression:
; CHECK:       add %r0, %r1
; CHECK:       and %r0, %r2
; CHECK:       jmpr %r7
  %tmp = add i16 %a, %b
  %res = and i16 %tmp, %c
  ret i16 %res
}
