; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32 < %s | FileCheck %s

;; ===========================================================================
;; ETCA arithmetic codegen tests — base 16-bit word + 16-bit pointer
;
;; Tests all base arithmetic instructions. Uses regex {{[...]}} to
;; accommodate register name suffixes (d/q/h) and extra movz/movs wrappers
;; that appear when the word size differs from the operation width.
;; ===========================================================================

;; --- ADD (register-register) ---

define i16 @add_rr(i16 %a, i16 %b) {
; CHECK-LABEL: add_rr:
; CHECK:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = add i16 %a, %b
  ret i16 %r
}

;; --- ADD with small immediate ---

define i16 @add_ri_small(i16 %a) {
; CHECK-LABEL: add_ri_small:
; CHECK:       {{add %r[0-9]+[dqh]?, [0-9-]+}}
; CHECK:       jmpr %r7
  %r = add i16 %a, 10
  ret i16 %r
}

define i16 @add_ri_zero(i16 %a) {
; CHECK-LABEL: add_ri_zero:
; CHECK:       {{add %r[0-9]+[dqh]?, 0}}
; CHECK:       jmpr %r7
  %r = add i16 %a, 0
  ret i16 %r
}

define i16 @add_ri_large(i16 %a) {
; CHECK-LABEL: add_ri_large:
; CHECK:       {{movz %r[0-9]+[dqh]?, 31}}
; CHECK:       {{slo %r[0-9]+[dqh]?, 8}}
; CHECK:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = add i16 %a, 1000
  ret i16 %r
}

;; --- SUB (register-register) ---

define i16 @sub_rr(i16 %a, i16 %b) {
; CHECK-LABEL: sub_rr:
; CHECK:       {{sub %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = sub i16 %a, %b
  ret i16 %r
}

define i16 @sub_ri_small(i16 %a) {
; CHECK-LABEL: sub_ri_small:
; CHECK:       {{sub %r[0-9]+[dqh]?, [0-9-]+}}
; CHECK:       jmpr %r7
  %r = sub i16 %a, 1
  ret i16 %r
}

define i16 @rsub_rr(i16 %a, i16 %b) {
; CHECK-LABEL: rsub_rr:
; CHECK:       {{sub %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = sub i16 %b, %a
  ret i16 %r
}

;; --- OR (register-register) ---

define i16 @or_rr(i16 %a, i16 %b) {
; CHECK-LABEL: or_rr:
; CHECK:       {{or %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = or i16 %a, %b
  ret i16 %r
}

define i16 @or_ri_small(i16 %a) {
; CHECK-LABEL: or_ri_small:
; CHECK:       {{movz %r[0-9]+[dqh]?, 1}}
; CHECK:       {{or %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = or i16 %a, 1
  ret i16 %r
}

;; --- XOR (register-register) ---

define i16 @xor_rr(i16 %a, i16 %b) {
; CHECK-LABEL: xor_rr:
; CHECK:       {{xor %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = xor i16 %a, %b
  ret i16 %r
}

define i16 @xor_ri_small(i16 %a) {
; CHECK-LABEL: xor_ri_small:
; CHECK:       {{movz %r[0-9]+[dqh]?, 15}}
; CHECK:       {{xor %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = xor i16 %a, 15
  ret i16 %r
}

;; --- AND (register-register) ---

define i16 @and_rr(i16 %a, i16 %b) {
; CHECK-LABEL: and_rr:
; CHECK:       {{and %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = and i16 %a, %b
  ret i16 %r
}

define i16 @and_ri_small(i16 %a) {
; CHECK-LABEL: and_ri_small:
; CHECK:       {{movz %r[0-9]+[dqh]?, 15}}
; CHECK:       {{and %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = and i16 %a, 15
  ret i16 %r
}

;; --- SLO (shift left) ---

define i16 @shift_left(i16 %a) {
; CHECK-LABEL: shift_left:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 2
  ret i16 %r
}

define i16 @shift_left_by_zero(i16 %a) {
; CHECK-LABEL: shift_left_by_zero:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 0
  ret i16 %r
}

define i16 @shift_left_by_one(i16 %a) {
; CHECK-LABEL: shift_left_by_one:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 1
  ret i16 %r
}

;; --- SHL uses SLO for groups of 5, ADDs for remainder (16-bit) ---
;; --- (wider widths fall back to linear ADD) ---

define i16 @shift_left_by_3(i16 %a) {
; CHECK-LABEL: shift_left_by_3:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 3
  ret i16 %r
}

define i16 @shift_left_by_5(i16 %a) {
; CHECK-LABEL: shift_left_by_5:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 5
  ret i16 %r
}

define i16 @shift_left_by_6(i16 %a) {
; CHECK-LABEL: shift_left_by_6:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 6
  ret i16 %r
}

define i16 @shift_left_by_7(i16 %a) {
; CHECK-LABEL: shift_left_by_7:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 7
  ret i16 %r
}

define i16 @shift_left_by_10(i16 %a) {
; CHECK-LABEL: shift_left_by_10:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 10
  ret i16 %r
}

define i16 @shift_left_by_15(i16 %a) {
; CHECK-LABEL: shift_left_by_15:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 15
  ret i16 %r
}

define i16 @shift_left_overflow(i16 %a) {
; CHECK-LABEL: shift_left_overflow:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, 16
  ret i16 %r
}

define i16 @shift_left_negative(i16 %a) {
; CHECK-LABEL: shift_left_negative:
; CHECK:       call __ashlhi3
; CHECK:       jmpr %r7
  %r = shl i16 %a, -1
  ret i16 %r
}

;; --- Commutative patterns ---

define i16 @add_commuted(i16 %a, i16 %b) {
; CHECK-LABEL: add_commuted:
; CHECK:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = add i16 %b, %a
  ret i16 %r
}

define i16 @or_commuted(i16 %a, i16 %b) {
; CHECK-LABEL: or_commuted:
; CHECK:       {{or %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = or i16 %b, %a
  ret i16 %r
}

;; --- Chained arithmetic ---

define i16 @chained_add_sub(i16 %x, i16 %y, i16 %z) {
; CHECK-LABEL: chained_add_sub:
; CHECK:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       {{sub %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %sum = add i16 %x, %y
  %res = sub i16 %sum, %z
  ret i16 %res
}

define i16 @three_op_expression(i16 %a, i16 %b, i16 %c) {
; CHECK-LABEL: three_op_expression:
; CHECK:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       {{and %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %tmp = add i16 %a, %b
  %res = and i16 %tmp, %c
  ret i16 %res
}
