; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; Test that i1 (boolean) loads and stores are correctly legalized.
; The legalizer must widen sub-MinLegal G_LOAD/G_STORE (s1) to the
; minimum legal scalar type (s8 with byte ext, s16 without).
; Without this fix, 'llc' would crash with:
;   LLVM ERROR: unable to legalize instruction: ... = G_LOAD ...
;
; Test all width/pointer combinations.

;--- i1 load, 16-bit word + 16-bit ptr (default config, with byte ext) ---
; RUN: llc -mtriple=etca-unknown-elf32 -mcpu=generic -O1 -filetype=asm %s -o - 2>&1 | FileCheck %s --check-prefix=LOAD16

;--- i1 load, 32-bit word + 32-bit ptr ---
; RUN: llc -mtriple=etca-unknown-elf32 -mcpu=generic -mattr=+ptr32,+32bit -O1 -filetype=asm %s -o - 2>&1 | FileCheck %s --check-prefix=LOAD32

;--- i1 load, 64-bit word + 64-bit ptr ---
; RUN: llc -mtriple=etca-unknown-elf32 -mcpu=generic -mattr=+ptr64,+64bit -O1 -filetype=asm %s -o - 2>&1 | FileCheck %s --check-prefix=LOAD64

;--- i1 load, 32-bit word + 64-bit ptr ---
; RUN: llc -mtriple=etca-unknown-elf32 -mcpu=generic -mattr=+ptr64,+32bit -O1 -filetype=asm %s -o - 2>&1 | FileCheck %s --check-prefix=LOAD32P64

;--- i1 load, 64-bit word + 32-bit ptr ---
; RUN: llc -mtriple=etca-unknown-elf32 -mcpu=generic -mattr=+ptr32,+64bit -O1 -filetype=asm %s -o - 2>&1 | FileCheck %s --check-prefix=LOAD64P32

;--- i1 store, 32-bit word + 32-bit ptr ---
; RUN: llc -mtriple=etca-unknown-elf32 -mcpu=generic -mattr=+ptr32,+32bit -O1 -filetype=asm %s -o - 2>&1 | FileCheck %s --check-prefix=STORE32

;--- i1 load/store, 32-bit word + 32-bit ptr, no byte extension ---
; RUN: llc -mtriple=etca-unknown-elf32 -mcpu=generic -mattr=+ptr32,+32bit,-byte -O1 -filetype=asm %s -o - 2>&1 | FileCheck %s --check-prefix=LOAD32NOBYTE

@global_bool = external global i1, align 4

define i1 @load_bool() {
; LOAD16-LABEL: load_bool:
; LOAD16:       ; %bb.0:
; LOAD16-NEXT:    movz %r0, global_bool{{$}}
; LOAD16-NEXT:    load %r0h, %r0h
; LOAD16-NEXT:    movz %r0h, %r0h
; LOAD16-NEXT:    jmpr %r7
;
; LOAD32-LABEL: load_bool:
; LOAD32:       ; %bb.0:
; LOAD32-NEXT:    movz %r0d, global_bool
; LOAD32-NEXT:    load %r0, %r0d
; LOAD32-NEXT:    movz %r0h, %r0h
; LOAD32-NEXT:    movs %r0, %r0
; LOAD32-NEXT:    jmpr %r7
;
; LOAD64-LABEL: load_bool:
; LOAD64:       ; %bb.0:
; LOAD64-NEXT:    movz %r0q, global_bool
; LOAD64-NEXT:    load %r0, %r0q
; LOAD64-NEXT:    movz %r0h, %r0h
; LOAD64-NEXT:    movs %r0, %r0
; LOAD64-NEXT:    jmpr %r7
;
; LOAD32P64-LABEL: load_bool:
; LOAD32P64:       ; %bb.0:
; LOAD32P64-NEXT:    movz %r0q, global_bool
; LOAD32P64-NEXT:    load %r0, %r0q
; LOAD32P64-NEXT:    movz %r0h, %r0h
; LOAD32P64-NEXT:    movs %r0, %r0
; LOAD32P64-NEXT:    jmpr %r7
;
; LOAD64P32-LABEL: load_bool:
; LOAD64P32:       ; %bb.0:
; LOAD64P32-NEXT:    movz %r0d, global_bool
; LOAD64P32-NEXT:    load %r0, %r0d
; LOAD64P32-NEXT:    movz %r0h, %r0h
; LOAD64P32-NEXT:    movs %r0, %r0
; LOAD64P32-NEXT:    jmpr %r7
;
; LOAD32NOBYTE-LABEL: load_bool:
; LOAD32NOBYTE:       ; %bb.0:
; LOAD32NOBYTE-NEXT:    movz %r0d, global_bool
; LOAD32NOBYTE-NEXT:    load %r0, %r0d
; LOAD32NOBYTE-NEXT:    movz %r0, %r0
; LOAD32NOBYTE-NEXT:    movs %r0, %r0
; LOAD32NOBYTE-NEXT:    jmpr %r7
  %.b = load i1, ptr @global_bool, align 4
  ret i1 %.b
}

define void @store_bool(i1 %val) {
; STORE32-LABEL: store_bool:
; STORE32:       ; %bb.0:
; STORE32-NEXT:    movz %r1d, global_bool
; STORE32-NEXT:    store %r0, %r1d
; STORE32-NEXT:    jmpr %r7
  store i1 %val, ptr @global_bool, align 4
  ret void
}
