; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s --check-prefixes=GN
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 < %s | FileCheck %s --check-prefixes=EW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s --check-prefixes=QW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32 < %s | FileCheck %s --check-prefixes=P64
; RUN: llc -march=etca -mcpu=generic -mattr=+rex < %s | FileCheck %s --check-prefixes=REX

;; ===========================================================================
;; ETCA calling convention mask tests
;;
;; Verifies that getCallPreservedMask() correctly selects CSR masks for
;; different calling conventions (Cold, PreserveMost, PreserveAll).
;;
;; Key invariant demonstrated by test:
;;   Calling a coldcc/preserve_mostcc function from a normal caller
;;   preserves more registers (R1, R2, R7 survive the call), so the
;;   caller does NOT need to spill them.  Calling a default-cc function
;;   requires the caller to save R1, R2 in callee-saved regs (R3/R4).
;;
;; On 16-bit (GN): normal_func saves R3,R4; call_cold does not (✓).
;; On 64-bit (QW/P64): extra GPRs available reduce spills in all cases,
;;   but the mask selection is still exercised and verified.
;; With REX extension: R13-R15 are callee-saved in addition to R3-R4.
;; ===========================================================================

declare i16 @ext_callee(i16)

;; ---------------------------------------------------------------------------
;; Test 1: Default CC — caller must save R1, R2 (caller-saved) before call
;;
;; The function has values in R1 and R2 (arguments v1, v2) needed after the
;; call.  Default CC does NOT preserve R1/R2, so they're moved to callee-saved
;; regs (R3, R4) before the call.
;; ---------------------------------------------------------------------------
define i16 @normal_func(i16 %v0, i16 %v1, i16 %v2) {
; GN-LABEL: normal_func:
; GN:       push %r5
; GN:  movz %r5, %r6
; GN:  push %r3
; GN:  push %r4
; GN:  movz %r3, %r1
; GN:  movz %r4, %r2
; GN:  call ext_callee
; GN:  add %r0, %r3
; GN:  add %r0, %r4
; GN:  movz %r6, %r5
; GN:  sub %r6, 4
; GN:  pop %r4
; GN:  pop %r3
; GN:  pop %r5
; GN:  jmpr %r7
;
; EW-LABEL: normal_func:
; EW:       push %r5
; EW:  movz %r5, %r6
; EW:  push %r3
; EW:  push %r4
; EW:  movz %r3, %r1d
; EW:  movz %r4, %r2d
; EW:  call ext_callee
; EW:  add %r0, %r3
; EW:  add %r0, %r4
; EW:  movz %r6, %r5
; EW:  sub %r6, 4
; EW:  pop %r4
; EW:  pop %r3
; EW:  pop %r5
; EW:  jmpr %r7
;
; QW-LABEL: normal_func:
; QW:       push %r5
; QW:  movz %r5, %r6
; QW:  call ext_callee
; QW:  add %r0, %r1
; QW:  add %r0, %r2
; QW:  movz %r6, %r5
; QW:  pop %r5
; QW:  jmpr %r7
;
; P64-LABEL: normal_func:
; P64:       push %r5
; P64:  movz %r5, %r6
; P64:  call ext_callee
; P64:  add %r0, %r1
; P64:  add %r0, %r2
; P64:  movz %r6, %r5
; P64:  pop %r5
; P64:  jmpr %r7
;
; REX-LABEL: normal_func:
; REX:       push %r5
; REX:  movz %r5, %r6
; REX:  push %r13
; REX:  push %r14
; REX:  push %r15
; REX:  call ext_callee
; REX:  add %r0, %r1
; REX:  add %r0, %r2
; REX:  movz %r6, %r5
; REX:  sub %r6, 6
; REX:  pop %r15
; REX:  pop %r14
; REX:  pop %r13
; REX:  pop %r5
; REX:  jmpr %r7
  %r1 = call i16 @ext_callee(i16 %v0)
  %r2 = add i16 %r1, %v1
  %r  = add i16 %r2, %v2
  ret i16 %r
}

;; ---------------------------------------------------------------------------
;; Test 2: Calling a ColdCC function — callee preserves everything except R0.
;;
;; Since coldcc preserves R1 and R2, the caller does NOT need to save them
;; before the call.  No extra push/pop (beyond R5/bp) needed.
;; Key observation: unlike normal_func, no R3/R4 save appears in GN/EW.
;; ---------------------------------------------------------------------------
declare coldcc i16 @cold_callee(i16)

define i16 @call_cold(i16 %v0, i16 %v1, i16 %v2) {
; GN-LABEL: call_cold:
; GN:       push %r5
; GN:  movz %r5, %r6
; GN:  call cold_callee
; GN:  add %r0, %r1
; GN:  add %r0, %r2
; GN:  movz %r6, %r5
; GN:  pop %r5
; GN:  jmpr %r7
;
; EW-LABEL: call_cold:
; EW:       push %r5
; EW:  movz %r5, %r6
; EW:  call cold_callee
; EW:  add %r0, %r1
; EW:  add %r0, %r2
; EW:  movz %r6, %r5
; EW:  pop %r5
; EW:  jmpr %r7
;
; QW-LABEL: call_cold:
; QW:       push %r5
; QW:  movz %r5, %r6
; QW:  call cold_callee
; QW:  add %r0, %r1
; QW:  add %r0, %r2
; QW:  movz %r6, %r5
; QW:  pop %r5
; QW:  jmpr %r7
;
; P64-LABEL: call_cold:
; P64:       push %r5
; P64:  movz %r5, %r6
; P64:  call cold_callee
; P64:  add %r0, %r1
; P64:  add %r0, %r2
; P64:  movz %r6, %r5
; P64:  pop %r5
; P64:  jmpr %r7
;
; REX-LABEL: call_cold:
; REX:       push %r5
; REX:  movz %r5, %r6
; REX:  push %r13
; REX:  push %r14
; REX:  push %r15
; REX:  call cold_callee
; REX:  add %r0, %r1
; REX:  add %r0, %r2
; REX:  movz %r6, %r5
; REX:  sub %r6, 6
; REX:  pop %r15
; REX:  pop %r14
; REX:  pop %r13
; REX:  pop %r5
; REX:  jmpr %r7
  %r1 = call coldcc i16 @cold_callee(i16 %v0)
  %r2 = add i16 %r1, %v1
  %r  = add i16 %r2, %v2
  ret i16 %r
}

;; ---------------------------------------------------------------------------
;; Test 3: Calling a PreserveMostCC function — same as ColdCC
;; ---------------------------------------------------------------------------
declare preserve_mostcc i16 @most_callee(i16)

define i16 @call_most(i16 %v0, i16 %v1, i16 %v2) {
; GN-LABEL: call_most:
; GN:       push %r5
; GN:  movz %r5, %r6
; GN:  call most_callee
; GN:  add %r0, %r1
; GN:  add %r0, %r2
; GN:  movz %r6, %r5
; GN:  pop %r5
; GN:  jmpr %r7
;
; EW-LABEL: call_most:
; EW:       push %r5
; EW:  movz %r5, %r6
; EW:  call most_callee
; EW:  add %r0, %r1
; EW:  add %r0, %r2
; EW:  movz %r6, %r5
; EW:  pop %r5
; EW:  jmpr %r7
;
; QW-LABEL: call_most:
; QW:       push %r5
; QW:  movz %r5, %r6
; QW:  call most_callee
; QW:  add %r0, %r1
; QW:  add %r0, %r2
; QW:  movz %r6, %r5
; QW:  pop %r5
; QW:  jmpr %r7
;
; P64-LABEL: call_most:
; P64:       push %r5
; P64:  movz %r5, %r6
; P64:  call most_callee
; P64:  add %r0, %r1
; P64:  add %r0, %r2
; P64:  movz %r6, %r5
; P64:  pop %r5
; P64:  jmpr %r7
;
; REX-LABEL: call_most:
; REX:       push %r5
; REX:  movz %r5, %r6
; REX:  push %r13
; REX:  push %r14
; REX:  push %r15
; REX:  call most_callee
; REX:  add %r0, %r1
; REX:  add %r0, %r2
; REX:  movz %r6, %r5
; REX:  sub %r6, 6
; REX:  pop %r15
; REX:  pop %r14
; REX:  pop %r13
; REX:  pop %r5
; REX:  jmpr %r7
  %r1 = call preserve_mostcc i16 @most_callee(i16 %v0)
  %r2 = add i16 %r1, %v1
  %r  = add i16 %r2, %v2
  ret i16 %r
}

;; ---------------------------------------------------------------------------
;; Test 4: Calling a PreserveAllCC function — preserves ALL registers
;;         including R0.  The effect on the caller is similar to ColdCC.
;; ---------------------------------------------------------------------------
declare preserve_allcc i16 @all_callee(i16)

define i16 @call_all(i16 %v0, i16 %v1, i16 %v2) {
; GN-LABEL: call_all:
; GN:       push %r5
; GN:  movz %r5, %r6
; GN:  call all_callee
; GN:  add %r0, %r1
; GN:  add %r0, %r2
; GN:  movz %r6, %r5
; GN:  pop %r5
; GN:  jmpr %r7
;
; EW-LABEL: call_all:
; EW:       push %r5
; EW:  movz %r5, %r6
; EW:  call all_callee
; EW:  add %r0, %r1
; EW:  add %r0, %r2
; EW:  movz %r6, %r5
; EW:  pop %r5
; EW:  jmpr %r7
;
; QW-LABEL: call_all:
; QW:       push %r5
; QW:  movz %r5, %r6
; QW:  push %r3
; QW:  push %r4
; QW:  movz %r3, %r1q
; QW:  movz %r4, %r2q
; QW:  call all_callee
; QW:  add %r0, %r3
; QW:  add %r0, %r4
; QW:  movz %r6, %r5
; QW:  sub %r6, 4
; QW:  pop %r4
; QW:  pop %r3
; QW:  pop %r5
; QW:  jmpr %r7
;
; P64-LABEL: call_all:
; P64:       push %r5
; P64:  movz %r5, %r6
; P64:  push %r3
; P64:  push %r4
; P64:  movz %r3, %r1q
; P64:  movz %r4, %r2q
; P64:  call all_callee
; P64:  add %r0, %r3
; P64:  add %r0, %r4
; P64:  movz %r6, %r5
; P64:  sub %r6, 4
; P64:  pop %r4
; P64:  pop %r3
; P64:  pop %r5
; P64:  jmpr %r7
;
; REX-LABEL: call_all:
; REX:       push %r5
; REX:  movz %r5, %r6
; REX:  push %r3
; REX:  push %r4
; REX:  movz %r3, %r1
; REX:  movz %r4, %r2
; REX:  call all_callee
; REX:  add %r0, %r3
; REX:  add %r0, %r4
; REX:  movz %r6, %r5
; REX:  sub %r6, 4
; REX:  pop %r4
; REX:  pop %r3
; REX:  pop %r5
; REX:  jmpr %r7
  %r1 = call preserve_allcc i16 @all_callee(i16 %v0)
  %r2 = add i16 %r1, %v1
  %r  = add i16 %r2, %v2
  ret i16 %r
}

;; ---------------------------------------------------------------------------
;; Test 5: Leaf ColdCC function (no calls) — just verifies no crash
;; ---------------------------------------------------------------------------
define coldcc i16 @coldcc_leaf(i16 %a, i16 %b) {
; GN-LABEL: coldcc_leaf:
; GN:       jmpr %r7
;
; EW-LABEL: coldcc_leaf:
; EW:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; EW:  jmpr %r7
;
; QW-LABEL: coldcc_leaf:
; QW:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; QW:  jmpr %r7
;
; P64-LABEL: coldcc_leaf:
; P64:       {{add %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; P64:  jmpr %r7
;
; REX-LABEL: coldcc_leaf:
; REX:       jmpr %r7
  %r = add i16 %a, %b
  ret i16 %r
}
