; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s --check-prefix=GN
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 < %s | FileCheck %s --check-prefix=DW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s --check-prefix=QW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s --check-prefix=QW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32 < %s | FileCheck %s --check-prefix=QW

;; ===========================================================================
;; ETCA calling-convention codegen tests
;;
;; Tests function calls, argument passing, and return values.  The ETCA
;; calling convention assigns:
;;   - First four i16 arguments to r0-r3
;;   - Remaining arguments on the stack (2-byte aligned)
;;   - Return value in r0 (i16) or r0-r1 pair (i32)
;;
;; Instructions covered:
;;   CALL_Pseudo → call, RET_Pseudo → ret,
;;   argument setup via registers and stack.
;;
;; Check-prefixes:
;;   GN = generic 16-bit word (base ISA)
;;   DW = 32-bit word (+dw)
;;   QW = 64-bit word (+qw)
;; ===========================================================================

;; --- No-argument call ---

declare i16 @callee_noarg()

define i16 @caller_noarg() {
; GN-LABEL: caller_noarg:
; GN:       call callee_noarg
; GN:       jmpr %r7
;
; DW-LABEL: caller_noarg:
; DW:       call callee_noarg
; DW:       jmpr %r7
;
; QW-LABEL: caller_noarg:
; QW:       call callee_noarg
; QW:       jmpr %r7
  %r = call i16 @callee_noarg()
  ret i16 %r
}

;; --- One-argument call ---

declare i16 @callee1(i16)

define i16 @caller_one_arg(i16 %x) {
; GN-LABEL: caller_one_arg:
; GN:       call callee1
; GN:       jmpr %r7
;
; DW-LABEL: caller_one_arg:
; DW:       call callee1
; DW:       jmpr %r7
;
; QW-LABEL: caller_one_arg:
; QW:       call callee1
; QW:       jmpr %r7
  %r = call i16 @callee1(i16 %x)
  ret i16 %r
}

;; --- Two-argument call ---

declare i16 @callee2(i16, i16)

define i16 @caller_two_args(i16 %x, i16 %y) {
; GN-LABEL: caller_two_args:
; GN:       call callee2
; GN:       jmpr %r7
;
; DW-LABEL: caller_two_args:
; DW:       call callee2
; DW:       jmpr %r7
;
; QW-LABEL: caller_two_args:
; QW:       call callee2
; QW:       jmpr %r7
  %r = call i16 @callee2(i16 %x, i16 %y)
  ret i16 %r
}

;; --- Three-argument call ---

declare i16 @callee3(i16, i16, i16)

define i16 @caller_three_args(i16 %x, i16 %y, i16 %z) {
; GN-LABEL: caller_three_args:
; GN:       call callee3
; GN:       jmpr %r7
;
; DW-LABEL: caller_three_args:
; DW:       call callee3
; DW:       jmpr %r7
;
; QW-LABEL: caller_three_args:
; QW:       call callee3
; QW:       jmpr %r7
  %r = call i16 @callee3(i16 %x, i16 %y, i16 %z)
  ret i16 %r
}

;; --- Four-argument call (all in registers r0-r3) ---

declare i16 @callee4(i16, i16, i16, i16)

define i16 @caller_four_args(i16 %a, i16 %b, i16 %c, i16 %d) {
; GN-LABEL: caller_four_args:
; GN:       call callee4
; GN:       jmpr %r7
;
; DW-LABEL: caller_four_args:
; DW:       call callee4
; DW:       jmpr %r7
;
; QW-LABEL: caller_four_args:
; QW:       call callee4
; QW:       jmpr %r7
  %r = call i16 @callee4(i16 %a, i16 %b, i16 %c, i16 %d)
  ret i16 %r
}

;; --- Call from within a function that has params too (register reuse) ---

declare i16 @transform(i16)

define i16 @chain_call(i16 %x) {
; GN-LABEL: chain_call:
; GN:       call transform
; GN:       jmpr %r7
;
; DW-LABEL: chain_call:
; DW:       call transform
; DW:       jmpr %r7
;
; QW-LABEL: chain_call:
; QW:       call transform
; QW:       jmpr %r7
  %r = call i16 @transform(i16 %x)
  ret i16 %r
}

;; --- Call with constant arguments ---

declare i16 @const_callee(i16, i16)

define i16 @caller_const_args() {
; GN-LABEL: caller_const_args:
; GN:       call const_callee
; GN:       jmpr %r7
;
; DW-LABEL: caller_const_args:
; DW:       call const_callee
; DW:       jmpr %r7
;
; QW-LABEL: caller_const_args:
; QW:       call const_callee
; QW:       jmpr %r7
  %r = call i16 @const_callee(i16 42, i16 7)
  ret i16 %r
}

;; --- i16 return value ---

define i16 @ret_i16(i16 %x) {
; GN-LABEL: ret_i16:
; GN:       jmpr %r7
;
; DW-LABEL: ret_i16:
; DW:       jmpr %r7
;
; QW-LABEL: ret_i16:
; QW:       jmpr %r7
  ret i16 %x
}

;; --- i32 return value in r0-r1 pair ---

define i32 @ret_i32(i32 %x) {
; GN-LABEL: ret_i32:
; GN:       jmpr %r7
;
; DW-LABEL: ret_i32:
; DW:       jmpr %r7
;
; QW-LABEL: ret_i32:
; QW:       jmpr %r7
  ret i32 %x
}

;; --- Void return ---

define void @ret_void() {
; GN-LABEL: ret_void:
; GN:       jmpr %r7
;
; DW-LABEL: ret_void:
; DW:       jmpr %r7
;
; QW-LABEL: ret_void:
; QW:       jmpr %r7
  ret void
}

;; --- Recursive call (exercises caller-save / stack) ---

define i16 @simple_recursion(i16 %n) {
; GN-LABEL: simple_recursion:
; GN:       cmp %r0, %r1
; GN:       beq
; GN:       br
; GN:       sub %r0, 1
; GN:       call simple_recursion
; GN:       jmpr %r7
;
; DW-LABEL: simple_recursion:
; DW:       cmp %r0, %r1
; DW:       beq
; DW:       br
; DW:       sub %r0, 1
; DW:       call simple_recursion
; DW:       jmpr %r7
;
; QW-LABEL: simple_recursion:
; QW:       cmp %r0, %r1
; QW:       beq
; QW:       br
; QW:       sub %r0, 1
; QW:       call simple_recursion
; QW:       jmpr %r7
  %cmp = icmp eq i16 %n, 0
  br i1 %cmp, label %base, label %recurse
base:
  ret i16 0
recurse:
  %nm1 = sub i16 %n, 1
  %r = call i16 @simple_recursion(i16 %nm1)
  ret i16 %r
}

;; --- Mutual recursion (declaration only) ---

declare i16 @even(i16)

define i16 @odd(i16 %n) {
; GN-LABEL: odd:
; GN:       cmp %r0, %r1
; GN:       beq
; GN:       sub %r0, 1
; GN:       call even
; GN:       jmpr %r7
;
; DW-LABEL: odd:
; DW:       cmp %r0, %r1
; DW:       beq
; DW:       sub %r0, 1
; DW:       call even
; DW:       jmpr %r7
;
; QW-LABEL: odd:
; QW:       cmp %r0, %r1
; QW:       beq
; QW:       sub %r0, 1
; QW:       call even
; QW:       jmpr %r7
  %cmp = icmp eq i16 %n, 0
  br i1 %cmp, label %base, label %recurse
base:
  ret i16 0
recurse:
  %nm1 = sub i16 %n, 1
  %r = call i16 @even(i16 %nm1)
  ret i16 %r
}
