; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s

;; ===========================================================================
;; ETCA calling-convention codegen tests
;;
;; Tests function calls, argument passing, and return values.  The ETCA
;; calling convention assigns:
;;   - First four i16 arguments to r0-r3
;;   - Remaining arguments on the stack (2-byte aligned)
;;   - Return value in r0 (i16) or r0-r1 pair (i32)
;;
;; Instructions covered:
;;   CALL_Pseudo → call, RET_Pseudo → ret,
;;   argument setup via registers and stack.
;; ===========================================================================

;; --- No-argument call ---

declare i16 @callee_noarg()

define i16 @caller_noarg() {
; CHECK-LABEL: caller_noarg:
; CHECK:       call callee_noarg
; CHECK:       jmpr %r7
  %r = call i16 @callee_noarg()
  ret i16 %r
}

;; --- One-argument call ---

declare i16 @callee1(i16)

define i16 @caller_one_arg(i16 %x) {
; CHECK-LABEL: caller_one_arg:
; CHECK:       call callee1
; CHECK:       jmpr %r7
  %r = call i16 @callee1(i16 %x)
  ret i16 %r
}

;; --- Two-argument call ---

declare i16 @callee2(i16, i16)

define i16 @caller_two_args(i16 %x, i16 %y) {
; CHECK-LABEL: caller_two_args:
; CHECK:       call callee2
; CHECK:       jmpr %r7
  %r = call i16 @callee2(i16 %x, i16 %y)
  ret i16 %r
}

;; --- Three-argument call ---

declare i16 @callee3(i16, i16, i16)

define i16 @caller_three_args(i16 %x, i16 %y, i16 %z) {
; CHECK-LABEL: caller_three_args:
; CHECK:       call callee3
; CHECK:       jmpr %r7
  %r = call i16 @callee3(i16 %x, i16 %y, i16 %z)
  ret i16 %r
}

;; --- Four-argument call (all in registers r0-r3) ---

declare i16 @callee4(i16, i16, i16, i16)

define i16 @caller_four_args(i16 %a, i16 %b, i16 %c, i16 %d) {
; CHECK-LABEL: caller_four_args:
; CHECK:       call callee4
; CHECK:       jmpr %r7
  %r = call i16 @callee4(i16 %a, i16 %b, i16 %c, i16 %d)
  ret i16 %r
}

;; --- Call from within a function that has params too (register reuse) ---

declare i16 @transform(i16)

define i16 @chain_call(i16 %x) {
; CHECK-LABEL: chain_call:
; CHECK:       call transform
; CHECK:       jmpr %r7
  %r = call i16 @transform(i16 %x)
  ret i16 %r
}

;; --- Call with constant arguments ---

declare i16 @const_callee(i16, i16)

define i16 @caller_const_args() {
; CHECK-LABEL: caller_const_args:
; CHECK:       movz %r0, 1
; CHECK:       slo %r0, 10
; CHECK:       movz %r1, 7
; CHECK:       call const_callee
; CHECK:       jmpr %r7
  %r = call i16 @const_callee(i16 42, i16 7)
  ret i16 %r
}

;; --- i16 return value ---

define i16 @ret_i16(i16 %x) {
; CHECK-LABEL: ret_i16:
; CHECK:       jmpr %r7
  ret i16 %x
}

;; --- i32 return value in r0-r1 pair ---

define i32 @ret_i32(i32 %x) {
; CHECK-LABEL: ret_i32:
; CHECK:       movz %r0d, %r0
; CHECK:       movz %r0, %r0d
; CHECK:       jmpr %r7
  ret i32 %x
}

;; --- Void return ---

define void @ret_void() {
; CHECK-LABEL: ret_void:
; CHECK:       jmpr %r7
  ret void
}

;; --- Recursive call (exercises caller-save / stack) ---

define i16 @simple_recursion(i16 %n) {
; CHECK-LABEL: simple_recursion:
; CHECK:       cmp %r0, %r1
; CHECK:       beq
; CHECK:       br
; CHECK:       sub %r0, %r1
; CHECK:       call simple_recursion
; CHECK:       jmpr %r7
  %cmp = icmp eq i16 %n, 0
  br i1 %cmp, label %base, label %recurse
base:
  ret i16 0
recurse:
  %nm1 = sub i16 %n, 1
  %r = call i16 @simple_recursion(i16 %nm1)
  ret i16 %r
}

;; --- Mutual recursion (declaration only) ---

declare i16 @even(i16)

define i16 @odd(i16 %n) {
; CHECK-LABEL: odd:
; CHECK:       cmp %r0, %r1
; CHECK:       beq
; CHECK:       sub %r0, %r1
; CHECK:       call even
; CHECK:       jmpr %r7
  %cmp = icmp eq i16 %n, 0
  br i1 %cmp, label %base, label %recurse
base:
  ret i16 0
recurse:
  %nm1 = sub i16 %n, 1
  %r = call i16 @even(i16 %nm1)
  ret i16 %r
}
