; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32 < %s | FileCheck %s

;; ===========================================================================
;; ETCA constants and moves codegen tests
;;
;; Uses regex {{...}} for register names.
;; ===========================================================================

define i16 @ret_small_const() {
; CHECK-LABEL: ret_small_const:
; CHECK:       {{movz %r[0-9]+[dqh]?, 0}}
; CHECK:       jmpr %r7
  ret i16 0
}

define i16 @ret_const_one() {
; CHECK-LABEL: ret_const_one:
; CHECK:       {{movz %r[0-9]+[dqh]?, 1}}
; CHECK:       jmpr %r7
  ret i16 1
}

define i16 @ret_large_const() {
; CHECK-LABEL: ret_large_const:
; CHECK:       {{mov[s z] %r[0-9]+[dqh]?, 31}}
; CHECK:       jmpr %r7
  ret i16 65535
}

define i16 @ret_neg_const() {
; CHECK-LABEL: ret_neg_const:
; CHECK:       {{mov[s z] %r[0-9]+[dqh]?, 31}}
; CHECK:       jmpr %r7
  ret i16 -1
}

define i16 @frame_index() {
; CHECK-LABEL: frame_index:
; CHECK:       sub %r6, 2
; CHECK:       {{store %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       {{load %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %slot = alloca i16, align 2
  store i16 42, ptr %slot
  %v = load i16, ptr %slot
  ret i16 %v
}

define i16 @pass_through(i16 %x) {
; CHECK-LABEL: pass_through:
; CHECK:       jmpr %r7
  ret i16 %x
}

define i16 @add_const(i16 %x) {
; CHECK-LABEL: add_const:
; CHECK:       {{add %r[0-9]+[dqh]?, 5}}
; CHECK:       jmpr %r7
  %r = add i16 %x, 5
  ret i16 %r
}

define i16 @and_const(i16 %x) {
; CHECK-LABEL: and_const:
; CHECK:       {{movz %r[0-9]+[dqh]?, 15}}
; CHECK:       {{and %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = and i16 %x, 15
  ret i16 %r
}

define i16 @add_zero(i16 %x) {
; CHECK-LABEL: add_zero:
; CHECK:       {{add %r[0-9]+[dqh]?, 0}}
; CHECK:       jmpr %r7
  %r = add i16 %x, 0
  ret i16 %r
}

define i16 @or_zero(i16 %x) {
; CHECK-LABEL: or_zero:
; CHECK:       {{movz %r[0-9]+[dqh]?, 0}}
; CHECK:       {{or %r[0-9]+[dqh]?, %r[0-9]+[dqh]?}}
; CHECK:       jmpr %r7
  %r = or i16 %x, 0
  ret i16 %r
}
