; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=etca32 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=etca64 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=etca32p64 < %s | FileCheck %s
; RUN: llc -march=etca -mcpu=etca64p32 < %s | FileCheck %s

;; ===========================================================================
;; ETCA constants and moves codegen tests
;;
;; Tests MOVZ (zero-extend move) and MOVS (sign-extend move) used for
;; constant materialisation, frame-index computation, and register-to-register
;; copies.  The ETCA backend maps ISD::Constant and ISD::FrameIndex to MOVZ.
;;
;; MOVZ:  movz $dst, $imm (5-bit immediate) — small constants
;; MOVZI: movz $dst, $imm  — large immediate (same mnemonic, RI encoding)
;; MOVS:  movs $dst, $src2 — sign-extending move
;; ===========================================================================

;; --- Return a small constant ---

define i16 @ret_small_const() {
; CHECK-LABEL: ret_small_const:
; CHECK:       movz %r0, 0
; CHECK:       jmpr %r7
  ret i16 0
}

define i16 @ret_const_one() {
; CHECK-LABEL: ret_const_one:
; CHECK:       movz %r0, 1
; CHECK:       jmpr %r7
  ret i16 1
}

;; --- Return a larger constant ---

define i16 @ret_large_const() {
; CHECK-LABEL: ret_large_const:
; CHECK:       movs %r0, 31
; CHECK:       jmpr %r7
  ret i16 65535
}

;; --- Return a negative constant ---

define i16 @ret_neg_const() {
; CHECK-LABEL: ret_neg_const:
; CHECK:       movs %r0, 31
; CHECK:       jmpr %r7
  ret i16 -1
}

;; --- FrameIndex access ---

define i16 @frame_index() {
; CHECK-LABEL: frame_index:
; CHECK:       sub %r6, 2
; CHECK:       store %r0, %r1
; CHECK:       load %r0, %r1
; CHECK:       jmpr %r7
  %slot = alloca i16, align 2
  store i16 42, ptr %slot
  %v = load i16, ptr %slot
  ret i16 %v
}

;; --- Parameter passed through ---

define i16 @pass_through(i16 %x) {
; CHECK-LABEL: pass_through:
; CHECK:       jmpr %r7
  ret i16 %x
}

;; --- Use constant in arithmetic ---

define i16 @add_const(i16 %x) {
; CHECK-LABEL: add_const:
; CHECK:       add %r0, 5
; CHECK:       jmpr %r7
  %r = add i16 %x, 5
  ret i16 %r
}

;; --- Constant with logical operation ---

define i16 @and_const(i16 %x) {
; CHECK-LABEL: and_const:
; CHECK:       movz %r1, 15
; CHECK:       and %r0, %r1
; CHECK:       jmpr %r7
  %r = and i16 %x, 15
  ret i16 %r
}

;; --- Constant zero as identity for ADD ---

define i16 @add_zero(i16 %x) {
; CHECK-LABEL: add_zero:
; CHECK:       add %r0, 0
; CHECK:       jmpr %r7
  %r = add i16 %x, 0
  ret i16 %r
}

;; --- Constant zero as identity for OR ---

define i16 @or_zero(i16 %x) {
; CHECK-LABEL: or_zero:
; CHECK:       movz %r1, 0
; CHECK:       or %r0, %r1
; CHECK:       jmpr %r7
  %r = or i16 %x, 0
  ret i16 %r
}
