; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s

;; ===========================================================================
;; ETCA fibonacci codegen test
;;
;; Tests recursive function calls with the Fibonacci sequence.
;; ===========================================================================

define i16 @fib(i16 %n) {
; CHECK-LABEL: fib:
; CHECK:       push %r5
; CHECK:       movz %r5, %r6
; CHECK:       sub %r6, 2
; CHECK:       store %r3, %r5
; CHECK:       movz %r1, 2
; CHECK:       cmp %r0, %r1
; CHECK:       bltu
; CHECK:       br
; CHECK:       movz %r2, 1
; CHECK:       sub %r2, %r0
; CHECK:       movz %r3, %r0
; CHECK:       movz %r0, %r2
; CHECK:       call fib
; CHECK:       movz %r2, %r0
; CHECK:       sub %r1, %r3
; CHECK:       movz %r0, %r1
; CHECK:       call fib
; CHECK:       add %r0, %r2
; CHECK:       jmpr %r7
  %1 = icmp ult i16 %n, 2
  br i1 %1, label %return, label %recurse

recurse:
  %n1 = sub i16 %n, 1
  %f1 = call i16 @fib(i16 %n1)
  %n2 = sub i16 %n, 2
  %f2 = call i16 @fib(i16 %n2)
  %r = add i16 %f1, %f2
  ret i16 %r

return:
  ret i16 %n
}
