; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s --check-prefixes=CHK,GN
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32,+dw < %s | FileCheck %s --check-prefixes=CHK,EW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+dw,+qw < %s | FileCheck %s --check-prefixes=CHK,QW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32,+dw,+qw < %s | FileCheck %s --check-prefixes=CHK,P64
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+dw,+qw < %s | FileCheck %s --check-prefixes=CHK,W64

;; ===========================================================================
;; ETCA Frame Index Elimination Tests
;;
;; Verifies that eliminateFrameIndex in ETCARegisterInfo.cpp correctly handles
;; LOAD and STORE frame index operands without corrupting the frame register.
;;
;; Two known pitfalls tested here:
;;
;;   1. LOAD reuses the destination register as address-computation scratch.
;;      This is safe because the dest register is dead before the LOAD,
;;      FrameReg (r5/r6) is reserved and can never be the same as dest,
;;      and hardware reads the address before writing the result.
;;      Verified by:  load %rN, (%rN)  — same register for dest and address
;;
;;   2. STORE must NOT modify FrameReg in place (e.g. add %r5, %r5, N followed
;;      by add %r5, %r5, -N), because an interrupt between the two would
;;      leave the frame register corrupted.  Instead, a scratch register
;;      from the register scavenger must be used.
;;      Verified by:  no 'add %r5, %r5' in any STORE sequence
;; ===========================================================================

;; --- 1. LOAD with non-zero frame offset ---
; Tests a simple alloca + store + load which produces a frame index at bp-2.
; The LOAD's destination register is reused for address computation.
define i16 @load_nonzero_offset(i16 %x) {
  %slot = alloca i16, align 2
  store i16 %x, ptr %slot
  %val = load i16, ptr %slot
  ret i16 %val
}

;; --- 2. Spill/reload across call ---
; Forces a callee-saved register spill.  The reload (LOAD from stack slot)
; should reuse the LOAD's destination register as the address scratch,
; producing "load %rN, (%rN)".
define i16 @spill_reload(i16 %v1, i16 %v2, i16 %v3, i16 %v4, i16 %v5) {
  call void @callee()
  %s1 = add i16 %v1, %v2
  %s2 = add i16 %s1, %v3
  %s3 = add i16 %s2, %v4
  %r = add i16 %s3, %v5
  ret i16 %r
}

declare void @callee()
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHK: {{.*}}
; EW: {{.*}}
; GN: {{.*}}
; P64: {{.*}}
; QW: {{.*}}
; W64: {{.*}}
