; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s --check-prefixes=CHK,GN
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32,+dw < %s | FileCheck %s --check-prefixes=CHK,EW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+dw,+qw < %s | FileCheck %s --check-prefixes=CHK,QW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32,+dw,+qw < %s | FileCheck %s --check-prefixes=CHK,P64
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+dw,+qw < %s | FileCheck %s --check-prefixes=CHK,W64

;; ===========================================================================
;; ETCA Frame Index Elimination Tests
;;
;; Verifies that eliminateFrameIndex in ETCARegisterInfo.cpp correctly handles
;; LOAD and STORE frame index operands without corrupting the frame register.
;;
;; Two known pitfalls tested here:
;;
;;   1. LOAD reuses the destination register as address-computation scratch.
;;      This is safe because the dest register is dead before the LOAD,
;;      FrameReg (r5/r6) is reserved and can never be the same as dest,
;;      and hardware reads the address before writing the result.
;;      Verified by:  load %rN, (%rN)  — same register for dest and address
;;
;;   2. STORE must NOT modify FrameReg in place (e.g. add %r5, %r5, N followed
;;      by add %r5, %r5, -N), because an interrupt between the two would
;;      leave the frame register corrupted.  Instead, a scratch register
;;      from the register scavenger must be used.
;;      Verified by:  no 'add %r5, %r5' in any STORE sequence
;; ===========================================================================

;; --- 1. LOAD with non-zero frame offset ---
; Tests a simple alloca + store + load which produces a frame index at bp-2.
; The LOAD's destination register is reused for address computation.
define i16 @load_nonzero_offset(i16 %x) {
; CHK-LABEL: load_nonzero_offset:
; CHK:         push %r5
; CHK-NEXT:    movz %r5, %r6
; CHK:         sub %r6, 2
; CHK:         movz %r1, %r5
; CHK:         add %r1, -2
; CHK:         store %r0, %r1
; CHK:         load %r0, %r1
; CHK:         movz %r6, %r5
; CHK:         pop %r5
; CHK:         jmpr %r7
  %slot = alloca i16, align 2
  store i16 %x, ptr %slot
  %val = load i16, ptr %slot
  ret i16 %val
}

;; --- 2. Spill/reload across call ---
; Forces a callee-saved register spill.  The reload (LOAD from stack slot)
; should reuse the LOAD's destination register as the address scratch,
; producing "load %rN, (%rN)".
define i16 @spill_reload(i16 %v1, i16 %v2, i16 %v3, i16 %v4, i16 %v5) {
; GN-LABEL: spill_reload:
; GN:         push %r5
; GN-NEXT:    movz %r5, %r6
; GN:         push %r4
; GN:         sub %r6, 2
; GN:         movz %r4, %r0
; GN:         movz %r0, %r5
; GN:         add %r0, 2
; GN:         load %r0, %r0
; GN:         movz %r7, %r5
; GN:         add %r7, -2
; GN:         store %r0, %r7
; GN:         call callee
; GN:         add %r4, %r1
; GN:         add %r4, %r2
; GN:         add %r4, %r3
; GN:         movz %r0, %r5
; GN:         add %r0, -2
; GN:         load %r0, %r0
; GN:         add %r4, %r0
; GN:         movz %r0, %r4
; GN:         movz %r6, %r5
; GN:         sub %r6, 2
; GN:         pop %r4
; GN:         pop %r5
; GN:         jmpr %r7
;
; EW-LABEL: spill_reload:
; EW:         push %r5
; EW-NEXT:    movz %r5, %r6
; EW:         sub %r6,
; EW:         call callee
; EW:         jmpr %r7
;
; QW-LABEL: spill_reload:
; QW:         push %r5
; QW-NEXT:    movz %r5, %r6
; QW:         sub %r6,
; QW:         call callee
; QW:         jmpr %r7
;
; P64-LABEL: spill_reload:
; P64:        push %r5
; P64-NEXT:   movz %r5, %r6
; P64:        sub %r6,
; P64:        call callee
; P64:        jmpr %r7
;
; W64-LABEL: spill_reload:
; W64:        push %r5
; W64-NEXT:   movz %r5, %r6
; W64:        sub %r6,
; W64:        call callee
; W64:        jmpr %r7
  call void @callee()
  %s1 = add i16 %v1, %v2
  %s2 = add i16 %s1, %v3
  %s3 = add i16 %s2, %v4
  %r = add i16 %s3, %v5
  ret i16 %r
}

declare void @callee()
