; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=etca-unknown-elf -march=etca -mcpu=generic -O1 < %s | FileCheck %s --check-prefix=GEN16
; RUN: llc -mtriple=etca-unknown-elf -march=etca -mcpu=generic -mattr=+ptr32,+32bit -O1 < %s | FileCheck %s --check-prefix=WS32
; RUN: llc -mtriple=etca-unknown-elf -march=etca -mcpu=generic -mattr=+ptr64,+64bit -O1 < %s | FileCheck %s --check-prefix=WS64
;
; Test that G_FREEZE is correctly legalized and selected for all word sizes.
; G_FREEZE is a pass-through (marks a value as non-poison).  At the MIR level
; it emits a MOVZ (register-to-register copy).  When the source and destination
; are in the same register class, a self-copy (movz %rN, %rN) may be eliminated
; by later passes (TwoAddressInstructionPass or machine copy optimizer).
; Cross-register-class copies (e.g., %r0h ← %r0h, %r0d ← %r0d, %r0q ← %r0q)
; are retained.

target datalayout = "e-m:e-p:16:16-i8:8-i16:16-i32:16-i64:16-f32:16-f64:16-a:0-n8:16:32-S32"
target triple = "etca-unknown-elf"

; --- freeze of i16 value ---
; On GEN16, the self-copy (movz %r0, %r0) is eliminated.
; On WS32/WS64, sign-extension for the return may add movs.
define i16 @freeze_i16(i16 %a) #0 {
; GEN16-LABEL: freeze_i16:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: freeze_i16:
; WS32:       ; %bb.0:
; WS32-NEXT:   	movz %r0, %r0
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: freeze_i16:
; WS64:       ; %bb.0:
; WS64-NEXT:   	movz %r0, %r0
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
  %f = freeze i16 %a
  ret i16 %f
}

; --- freeze of i32 value ---
; On GEN16, the i32 value lives in a d-register, so movz %r0d, %r0d is retained.
; On WS32, the self-copy is eliminated (i32 is legal, same register class).
; On WS64, sign-extension may add movs.
define i32 @freeze_i32(i32 %a) #0 {
; GEN16-LABEL: freeze_i32:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	movz %r0d, %r0d
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: freeze_i32:
; WS32:       ; %bb.0:
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: freeze_i32:
; WS64:       ; %bb.0:
; WS64-NEXT:   	movz %r0d, %r0d
; WS64-NEXT:   	movs %r0d, %r0d
; WS64-NEXT:   	jmpr %r7
  %f = freeze i32 %a
  ret i32 %f
}

; --- freeze of i64 value ---
; On GEN16/WS32, i64 lives in a q-register, so movz %r0q, %r0q is retained.
; On WS64, self-copy eliminated.
define i64 @freeze_i64(i64 %a) #0 {
; GEN16-LABEL: freeze_i64:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	movz %r0q, %r0q
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: freeze_i64:
; WS32:       ; %bb.0:
; WS32-NEXT:   	movz %r0q, %r0q
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: freeze_i64:
; WS64:       ; %bb.0:
; WS64-NEXT:   	jmpr %r7
  %f = freeze i64 %a
  ret i64 %f
}

; --- freeze that feeds into an add ---
define i16 @freeze_add(i16 %a, i16 %b) #0 {
; GEN16-LABEL: freeze_add:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	add %r0, %r1
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: freeze_add:
; WS32:       ; %bb.0:
; WS32-NEXT:   	movz %r0, %r0
; WS32-NEXT:   	add %r0, %r1
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: freeze_add:
; WS64:       ; %bb.0:
; WS64-NEXT:   	movz %r0, %r0
; WS64-NEXT:   	add %r0, %r1
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
  %f = freeze i16 %a
  %r = add i16 %f, %b
  ret i16 %r
}

; --- freeze of i1 (bool) value ---
; i1 is widened to s16 (or s8 with byte ext), then frozen.
; The freeze may be eliminated if the copy is to the same register.
define i1 @freeze_i1(i1 %a) #0 {
; GEN16-LABEL: freeze_i1:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: freeze_i1:
; WS32:       ; %bb.0:
; WS32-NEXT:   	movz %r0, %r0
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: freeze_i1:
; WS64:       ; %bb.0:
; WS64-NEXT:   	movz %r0, %r0
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
  %f = freeze i1 %a
  ret i1 %f
}

; --- freeze of a pointer value ---
; Pointer type p0 should also be legal for G_FREEZE.
define ptr @freeze_ptr(ptr %a) #0 {
; GEN16-LABEL: freeze_ptr:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: freeze_ptr:
; WS32:       ; %bb.0:
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: freeze_ptr:
; WS64:       ; %bb.0:
; WS64-NEXT:   	jmpr %r7
  %f = freeze ptr %a
  ret ptr %f
}

attributes #0 = { nounwind }
