; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=etca-unknown-elf -march=etca -mcpu=generic -O1 < %s | FileCheck %s --check-prefix=GEN16
; RUN: llc -mtriple=etca-unknown-elf -march=etca -mcpu=generic -mattr=+ptr32,+32bit -O1 < %s | FileCheck %s --check-prefix=WS32
; RUN: llc -mtriple=etca-unknown-elf -march=etca -mcpu=generic -mattr=+ptr64,+64bit -O1 < %s | FileCheck %s --check-prefix=WS64
; RUN: llc -mtriple=etca-unknown-elf -march=etca -mcpu=generic -mattr=+byte -O1 < %s | FileCheck %s --check-prefix=BYTE
;
; Test that i1 (s1) values in PHI, constants, and returns are correctly
; legalized.  The legalizer widens s1 to MinLegal (s16 without +byte,
; s8 with +byte).  The instruction selector handles the widened types
; via COPY bridges and MOVZ/MOVS at the appropriate widths.
;
; This also covers the original crash reproducer:
;   llc -march=etca -mcpu=generic -mattr=+ptr32,+32bit -O1
; where a phi i1 [ false, ... ] produced G_PHI with s1, which was not
; handled by the legalizer.

target datalayout = "e-m:e-p:16:16-i8:8-i16:16-i32:16-i64:16-f32:16-f64:16-a:0-n8:16:32-S32"
target triple = "etca-unknown-elf"

; --- phi i1 with constant false ---
define i1 @phi_i1_false() #0 {
; GEN16-LABEL: phi_i1_false:
; GEN16:       ; %bb.0:                                ; %entry
; GEN16-NEXT:   	movz %r0h, 0
; GEN16-NEXT:   	; %bb.1:                                ; %end
; GEN16-NEXT:   	movz %r0h, %r0h
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: phi_i1_false:
; WS32:       ; %bb.0:                                ; %entry
; WS32-NEXT:   	movz %r0h, 0
; WS32-NEXT:   	; %bb.1:                                ; %end
; WS32-NEXT:   	movz %r0h, %r0h
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: phi_i1_false:
; WS64:       ; %bb.0:                                ; %entry
; WS64-NEXT:   	movz %r0h, 0
; WS64-NEXT:   	; %bb.1:                                ; %end
; WS64-NEXT:   	movz %r0h, %r0h
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
;
; BYTE-LABEL: phi_i1_false:
; BYTE:       ; %bb.0:                                ; %entry
; BYTE-NEXT:   	movz %r0h, 0
; BYTE-NEXT:   	; %bb.1:                                ; %end
; BYTE-NEXT:   	movz %r0h, %r0h
; BYTE-NEXT:   	jmpr %r7
;
entry:
  br label %end
end:
  %r = phi i1 [ false, %entry ]
  ret i1 %r
}

; --- phi i1 with constant true ---
define i1 @phi_i1_true() #0 {
; GEN16-LABEL: phi_i1_true:
; GEN16:       ; %bb.0:                                ; %entry
; GEN16-NEXT:   	movz %r0h, 1
; GEN16-NEXT:   	; %bb.1:                                ; %end
; GEN16-NEXT:   	movz %r0h, %r0h
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: phi_i1_true:
; WS32:       ; %bb.0:                                ; %entry
; WS32-NEXT:   	movz %r0h, 1
; WS32-NEXT:   	; %bb.1:                                ; %end
; WS32-NEXT:   	movz %r0h, %r0h
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: phi_i1_true:
; WS64:       ; %bb.0:                                ; %entry
; WS64-NEXT:   	movz %r0h, 1
; WS64-NEXT:   	; %bb.1:                                ; %end
; WS64-NEXT:   	movz %r0h, %r0h
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
;
; BYTE-LABEL: phi_i1_true:
; BYTE:       ; %bb.0:                                ; %entry
; BYTE-NEXT:   	movz %r0h, 1
; BYTE-NEXT:   	; %bb.1:                                ; %end
; BYTE-NEXT:   	movz %r0h, %r0h
; BYTE-NEXT:   	jmpr %r7
;
entry:
  br label %end
end:
  %r = phi i1 [ true, %entry ]
  ret i1 %r
}

; --- phi i1 from argument ---
define i1 @phi_i1_arg(i1 %x) #0 {
; GEN16-LABEL: phi_i1_arg:
; GEN16:       ; %bb.0:                                ; %entry
; GEN16-NEXT:   	; %bb.1:                                ; %end
; GEN16-NEXT:   	movz %r0h, %r0h
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: phi_i1_arg:
; WS32:       ; %bb.0:                                ; %entry
; WS32-NEXT:   	; %bb.1:                                ; %end
; WS32-NEXT:   	movz %r0h, %r0h
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: phi_i1_arg:
; WS64:       ; %bb.0:                                ; %entry
; WS64-NEXT:   	; %bb.1:                                ; %end
; WS64-NEXT:   	movz %r0h, %r0h
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
;
; BYTE-LABEL: phi_i1_arg:
; BYTE:       ; %bb.0:                                ; %entry
; BYTE-NEXT:   	; %bb.1:                                ; %end
; BYTE-NEXT:   	movz %r0h, %r0h
; BYTE-NEXT:   	jmpr %r7
;
entry:
  br label %end
end:
  %r = phi i1 [ %x, %entry ]
  ret i1 %r
}

; --- constant i1 false ---
define i1 @const_false() #0 {
; GEN16-LABEL: const_false:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	movz %r0h, 0
; GEN16-NEXT:   	movz %r0h, %r0h
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: const_false:
; WS32:       ; %bb.0:
; WS32-NEXT:   	movz %r0h, 0
; WS32-NEXT:   	movz %r0h, %r0h
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: const_false:
; WS64:       ; %bb.0:
; WS64-NEXT:   	movz %r0h, 0
; WS64-NEXT:   	movz %r0h, %r0h
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
;
; BYTE-LABEL: const_false:
; BYTE:       ; %bb.0:
; BYTE-NEXT:   	movz %r0h, 0
; BYTE-NEXT:   	movz %r0h, %r0h
; BYTE-NEXT:   	jmpr %r7
;
  ret i1 false
}

; --- constant i1 true ---
define i1 @const_true() #0 {
; GEN16-LABEL: const_true:
; GEN16:       ; %bb.0:
; GEN16-NEXT:   	movz %r0h, 1
; GEN16-NEXT:   	movz %r0h, %r0h
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: const_true:
; WS32:       ; %bb.0:
; WS32-NEXT:   	movz %r0h, 1
; WS32-NEXT:   	movz %r0h, %r0h
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: const_true:
; WS64:       ; %bb.0:
; WS64-NEXT:   	movz %r0h, 1
; WS64-NEXT:   	movz %r0h, %r0h
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
;
; BYTE-LABEL: const_true:
; BYTE:       ; %bb.0:
; BYTE-NEXT:   	movz %r0h, 1
; BYTE-NEXT:   	movz %r0h, %r0h
; BYTE-NEXT:   	jmpr %r7
;
  ret i1 true
}

; --- Exact reproducer from the bug report: phi i1 with 32-bit data layout ---
; This matches the original crash: llc -march=etca -mcpu=generic -mattr=+ptr32,+32bit -O1
define i1 @D_GrabMouseCallback() #0 {
; GEN16-LABEL: D_GrabMouseCallback:
; GEN16:       ; %bb.0:                                ; %entry
; GEN16-NEXT:   	movz %r0h, 0
; GEN16-NEXT:   	; %bb.1:                                ; %land.end
; GEN16-NEXT:   	movz %r0h, %r0h
; GEN16-NEXT:   	jmpr %r7
;
; WS32-LABEL: D_GrabMouseCallback:
; WS32:       ; %bb.0:                                ; %entry
; WS32-NEXT:   	movz %r0h, 0
; WS32-NEXT:   	; %bb.1:                                ; %land.end
; WS32-NEXT:   	movz %r0h, %r0h
; WS32-NEXT:   	movs %r0, %r0
; WS32-NEXT:   	jmpr %r7
;
; WS64-LABEL: D_GrabMouseCallback:
; WS64:       ; %bb.0:                                ; %entry
; WS64-NEXT:   	movz %r0h, 0
; WS64-NEXT:   	; %bb.1:                                ; %land.end
; WS64-NEXT:   	movz %r0h, %r0h
; WS64-NEXT:   	movs %r0, %r0
; WS64-NEXT:   	jmpr %r7
;
; BYTE-LABEL: D_GrabMouseCallback:
; BYTE:       ; %bb.0:                                ; %entry
; BYTE-NEXT:   	movz %r0h, 0
; BYTE-NEXT:   	; %bb.1:                                ; %land.end
; BYTE-NEXT:   	movz %r0h, %r0h
; BYTE-NEXT:   	jmpr %r7
;
entry:
  br label %land.end
land.end:
  %0 = phi i1 [ false, %entry ]
  ret i1 %0
}

attributes #0 = { noinline optnone }
