; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; Test i16 min/max on generic (16-bit word) subtarget.
;
; RUN: llc -mtriple=etca-unknown-elf -mcpu=generic < %s \
; RUN:   | FileCheck %s --check-prefix=GEN16

; --- i16 min/max ---

define i16 @smin_i16(i16 %a, i16 %b) {
; GEN16-LABEL: smin_i16:
; GEN16:       cmp %r0, %r1
; GEN16:       blt .L{{[.A-Z0-9_]+}}
; GEN16:       movz %r0, %r1
; GEN16:       jmpr %r7
  %r = call i16 @llvm.smin.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @smax_i16(i16 %a, i16 %b) {
; GEN16-LABEL: smax_i16:
; GEN16:       cmp %r0, %r1
; GEN16:       bgt .L{{[.A-Z0-9_]+}}
; GEN16:       movz %r0, %r1
; GEN16:       jmpr %r7
  %r = call i16 @llvm.smax.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @umin_i16(i16 %a, i16 %b) {
; GEN16-LABEL: umin_i16:
; GEN16:       cmp %r0, %r1
; GEN16:       bltu .L{{[.A-Z0-9_]+}}
; GEN16:       movz %r0, %r1
; GEN16:       jmpr %r7
  %r = call i16 @llvm.umin.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @umax_i16(i16 %a, i16 %b) {
; GEN16-LABEL: umax_i16:
; GEN16:       cmp %r0, %r1
; GEN16:       bgtu .L{{[.A-Z0-9_]+}}
; GEN16:       movz %r0, %r1
; GEN16:       jmpr %r7
  %r = call i16 @llvm.umax.i16(i16 %a, i16 %b)
  ret i16 %r
}

declare i16 @llvm.smin.i16(i16, i16)
declare i16 @llvm.smax.i16(i16, i16)
declare i16 @llvm.umin.i16(i16, i16)
declare i16 @llvm.umax.i16(i16, i16)
