; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; Test i8 and i16 min/max on 16-bit word + byte extension subtarget.
;
; RUN: llc -mtriple=etca-unknown-elf -mcpu=generic -mattr=+byte < %s \
; RUN:   | FileCheck %s --check-prefix=BYTE16

; --- i8 min/max ---

define i8 @smin_i8(i8 %a, i8 %b) {
; BYTE16-LABEL: smin_i8:
; BYTE16:       cmp %r0h, %r1h
; BYTE16:       blt .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       movs %r0h, %r0h
; BYTE16:       jmpr %r7
  %r = call i8 @llvm.smin.i8(i8 %a, i8 %b)
  ret i8 %r
}

define i8 @smax_i8(i8 %a, i8 %b) {
; BYTE16-LABEL: smax_i8:
; BYTE16:       cmp %r0h, %r1h
; BYTE16:       bgt .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       movs %r0h, %r0h
; BYTE16:       jmpr %r7
  %r = call i8 @llvm.smax.i8(i8 %a, i8 %b)
  ret i8 %r
}

define i8 @umin_i8(i8 %a, i8 %b) {
; BYTE16-LABEL: umin_i8:
; BYTE16:       cmp %r0h, %r1h
; BYTE16:       bltu .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       movs %r0h, %r0h
; BYTE16:       jmpr %r7
  %r = call i8 @llvm.umin.i8(i8 %a, i8 %b)
  ret i8 %r
}

define i8 @umax_i8(i8 %a, i8 %b) {
; BYTE16-LABEL: umax_i8:
; BYTE16:       cmp %r0h, %r1h
; BYTE16:       bgtu .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       movs %r0h, %r0h
; BYTE16:       jmpr %r7
  %r = call i8 @llvm.umax.i8(i8 %a, i8 %b)
  ret i8 %r
}

; --- i16 min/max ---

define i16 @smin_i16(i16 %a, i16 %b) {
; BYTE16-LABEL: smin_i16:
; BYTE16:       cmp %r0, %r1
; BYTE16:       blt .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       jmpr %r7
  %r = call i16 @llvm.smin.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @smax_i16(i16 %a, i16 %b) {
; BYTE16-LABEL: smax_i16:
; BYTE16:       cmp %r0, %r1
; BYTE16:       bgt .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       jmpr %r7
  %r = call i16 @llvm.smax.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @umin_i16(i16 %a, i16 %b) {
; BYTE16-LABEL: umin_i16:
; BYTE16:       cmp %r0, %r1
; BYTE16:       bltu .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       jmpr %r7
  %r = call i16 @llvm.umin.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @umax_i16(i16 %a, i16 %b) {
; BYTE16-LABEL: umax_i16:
; BYTE16:       cmp %r0, %r1
; BYTE16:       bgtu .L{{[.A-Z0-9_]+}}
; BYTE16:       movz %r0, %r1
; BYTE16:       jmpr %r7
  %r = call i16 @llvm.umax.i16(i16 %a, i16 %b)
  ret i16 %r
}

declare i8 @llvm.smin.i8(i8, i8)
declare i8 @llvm.smax.i8(i8, i8)
declare i8 @llvm.umin.i8(i8, i8)
declare i8 @llvm.umax.i8(i8, i8)
declare i16 @llvm.smin.i16(i16, i16)
declare i16 @llvm.smax.i16(i16, i16)
declare i16 @llvm.umin.i16(i16, i16)
declare i16 @llvm.umax.i16(i16, i16)
