; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; Test that G_SMIN, G_SMAX, G_UMIN, G_UMAX are lowered to CMP + SELECT
; for all supported word/pointer width combinations.
;
; For 16-bit-only subtargets, see minmax-i16.ll.
; For byte-extension subtargets, see minmax-byte.ll.
;
; RUN: llc -mtriple=etca-unknown-elf -mcpu=generic -mattr=+32bit,+64bit,+byte < %s \
; RUN:   | FileCheck %s --check-prefix=MAX

; --- i8 min/max ---

define i8 @smin_i8(i8 %a, i8 %b) {
; MAX-LABEL: smin_i8:
; MAX:       cmp %r0h, %r1h
; MAX:       blt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       movs %r0h, %r0h
; MAX:       jmpr %r7
  %r = call i8 @llvm.smin.i8(i8 %a, i8 %b)
  ret i8 %r
}

define i8 @smax_i8(i8 %a, i8 %b) {
; MAX-LABEL: smax_i8:
; MAX:       cmp %r0h, %r1h
; MAX:       bgt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       movs %r0h, %r0h
; MAX:       jmpr %r7
  %r = call i8 @llvm.smax.i8(i8 %a, i8 %b)
  ret i8 %r
}

define i8 @umin_i8(i8 %a, i8 %b) {
; MAX-LABEL: umin_i8:
; MAX:       cmp %r0h, %r1h
; MAX:       bltu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       movs %r0h, %r0h
; MAX:       jmpr %r7
  %r = call i8 @llvm.umin.i8(i8 %a, i8 %b)
  ret i8 %r
}

define i8 @umax_i8(i8 %a, i8 %b) {
; MAX-LABEL: umax_i8:
; MAX:       cmp %r0h, %r1h
; MAX:       bgtu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       movs %r0h, %r0h
; MAX:       jmpr %r7
  %r = call i8 @llvm.umax.i8(i8 %a, i8 %b)
  ret i8 %r
}

; --- i16 min/max ---

define i16 @smin_i16(i16 %a, i16 %b) {
; MAX-LABEL: smin_i16:
; MAX:       cmp %r0, %r1
; MAX:       blt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       jmpr %r7
  %r = call i16 @llvm.smin.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @smax_i16(i16 %a, i16 %b) {
; MAX-LABEL: smax_i16:
; MAX:       cmp %r0, %r1
; MAX:       bgt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       jmpr %r7
  %r = call i16 @llvm.smax.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @umin_i16(i16 %a, i16 %b) {
; MAX-LABEL: umin_i16:
; MAX:       cmp %r0, %r1
; MAX:       bltu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       jmpr %r7
  %r = call i16 @llvm.umin.i16(i16 %a, i16 %b)
  ret i16 %r
}

define i16 @umax_i16(i16 %a, i16 %b) {
; MAX-LABEL: umax_i16:
; MAX:       cmp %r0, %r1
; MAX:       bgtu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0, %r1
; MAX:       jmpr %r7
  %r = call i16 @llvm.umax.i16(i16 %a, i16 %b)
  ret i16 %r
}

; --- i32 min/max ---

define i32 @smin_i32(i32 %a, i32 %b) {
; MAX-LABEL: smin_i32:
; MAX:       cmp %r0d, %r1d
; MAX:       blt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0d, %r1d
; MAX:       jmpr %r7
  %r = call i32 @llvm.smin.i32(i32 %a, i32 %b)
  ret i32 %r
}

define i32 @smax_i32(i32 %a, i32 %b) {
; MAX-LABEL: smax_i32:
; MAX:       cmp %r0d, %r1d
; MAX:       bgt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0d, %r1d
; MAX:       jmpr %r7
  %r = call i32 @llvm.smax.i32(i32 %a, i32 %b)
  ret i32 %r
}

define i32 @umin_i32(i32 %a, i32 %b) {
; MAX-LABEL: umin_i32:
; MAX:       cmp %r0d, %r1d
; MAX:       bltu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0d, %r1d
; MAX:       jmpr %r7
  %r = call i32 @llvm.umin.i32(i32 %a, i32 %b)
  ret i32 %r
}

define i32 @umax_i32(i32 %a, i32 %b) {
; MAX-LABEL: umax_i32:
; MAX:       cmp %r0d, %r1d
; MAX:       bgtu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0d, %r1d
; MAX:       jmpr %r7
  %r = call i32 @llvm.umax.i32(i32 %a, i32 %b)
  ret i32 %r
}

; --- i64 min/max ---

define i64 @smin_i64(i64 %a, i64 %b) {
; MAX-LABEL: smin_i64:
; MAX:       cmp %r0q, %r1q
; MAX:       blt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0q, %r1q
; MAX:       jmpr %r7
  %r = call i64 @llvm.smin.i64(i64 %a, i64 %b)
  ret i64 %r
}

define i64 @smax_i64(i64 %a, i64 %b) {
; MAX-LABEL: smax_i64:
; MAX:       cmp %r0q, %r1q
; MAX:       bgt .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0q, %r1q
; MAX:       jmpr %r7
  %r = call i64 @llvm.smax.i64(i64 %a, i64 %b)
  ret i64 %r
}

define i64 @umin_i64(i64 %a, i64 %b) {
; MAX-LABEL: umin_i64:
; MAX:       cmp %r0q, %r1q
; MAX:       bltu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0q, %r1q
; MAX:       jmpr %r7
  %r = call i64 @llvm.umin.i64(i64 %a, i64 %b)
  ret i64 %r
}

define i64 @umax_i64(i64 %a, i64 %b) {
; MAX-LABEL: umax_i64:
; MAX:       cmp %r0q, %r1q
; MAX:       bgtu .L{{[.A-Z0-9_]+}}
; MAX:       movz %r0q, %r1q
; MAX:       jmpr %r7
  %r = call i64 @llvm.umax.i64(i64 %a, i64 %b)
  ret i64 %r
}

declare i8 @llvm.smin.i8(i8, i8)
declare i8 @llvm.smax.i8(i8, i8)
declare i8 @llvm.umin.i8(i8, i8)
declare i8 @llvm.umax.i8(i8, i8)

declare i16 @llvm.smin.i16(i16, i16)
declare i16 @llvm.smax.i16(i16, i16)
declare i16 @llvm.umin.i16(i16, i16)
declare i16 @llvm.umax.i16(i16, i16)

declare i32 @llvm.smin.i32(i32, i32)
declare i32 @llvm.smax.i32(i32, i32)
declare i32 @llvm.umin.i32(i32, i32)
declare i32 @llvm.umax.i32(i32, i32)

declare i64 @llvm.smin.i64(i64, i64)
declare i64 @llvm.smax.i64(i64, i64)
declare i64 @llvm.umin.i64(i64, i64)
declare i64 @llvm.umax.i64(i64, i64)
