; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --no-generate-mir --nocpp
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+dw,+qw -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN64

; Test that 64-bit MUL/DIV/REM operations are legalized as libcalls on
; CPUs with the QW extension (word size >= 64).

define i64 @mul64(i64 %a, i64 %b) {
; GEN64-LABEL: name: mul64
; GEN64: CALL_Pseudo &__muldi3
  %r = mul i64 %a, %b
  ret i64 %r
}

define i64 @sdiv64(i64 %a, i64 %b) {
; GEN64-LABEL: name: sdiv64
; GEN64: CALL_Pseudo &__divdi3
  %r = sdiv i64 %a, %b
  ret i64 %r
}

define i64 @udiv64(i64 %a, i64 %b) {
; GEN64-LABEL: name: udiv64
; GEN64: CALL_Pseudo &__udivdi3
  %r = udiv i64 %a, %b
  ret i64 %r
}

define i64 @srem64(i64 %a, i64 %b) {
; GEN64-LABEL: name: srem64
; GEN64: CALL_Pseudo &__moddi3
  %r = srem i64 %a, %b
  ret i64 %r
}

define i64 @urem64(i64 %a, i64 %b) {
; GEN64-LABEL: name: urem64
; GEN64: CALL_Pseudo &__umoddi3
  %r = urem i64 %a, %b
  ret i64 %r
}
