; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --no-generate-mir --nocpp
; RUN: llc -march=etca -mcpu=generic -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN16
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN64

; Test that 16-bit MUL/DIV/REM operations are legalized as libcalls on all CPUs.

define i16 @mul16(i16 %a, i16 %b) {
; GEN16-LABEL: name: mul16
; GEN16: CALL_Pseudo &__mulhi3
; GEN32-LABEL: name: mul16
; GEN32: CALL_Pseudo &__mulhi3
; GEN64-LABEL: name: mul16
; GEN64: CALL_Pseudo &__mulhi3
  %r = mul i16 %a, %b
  ret i16 %r
}

define i16 @sdiv16(i16 %a, i16 %b) {
; GEN16-LABEL: name: sdiv16
; GEN16: CALL_Pseudo &__divhi3
; GEN32-LABEL: name: sdiv16
; GEN32: CALL_Pseudo &__divhi3
; GEN64-LABEL: name: sdiv16
; GEN64: CALL_Pseudo &__divhi3
  %r = sdiv i16 %a, %b
  ret i16 %r
}

define i16 @udiv16(i16 %a, i16 %b) {
; GEN16-LABEL: name: udiv16
; GEN16: CALL_Pseudo &__udivhi3
; GEN32-LABEL: name: udiv16
; GEN32: CALL_Pseudo &__udivhi3
; GEN64-LABEL: name: udiv16
; GEN64: CALL_Pseudo &__udivhi3
  %r = udiv i16 %a, %b
  ret i16 %r
}

define i16 @srem16(i16 %a, i16 %b) {
; GEN16-LABEL: name: srem16
; GEN16: CALL_Pseudo &__modhi3
; GEN32-LABEL: name: srem16
; GEN32: CALL_Pseudo &__modhi3
; GEN64-LABEL: name: srem16
; GEN64: CALL_Pseudo &__modhi3
  %r = srem i16 %a, %b
  ret i16 %r
}

define i16 @urem16(i16 %a, i16 %b) {
; GEN16-LABEL: name: urem16
; GEN16: CALL_Pseudo &__umodhi3
; GEN32-LABEL: name: urem16
; GEN32: CALL_Pseudo &__umodhi3
; GEN64-LABEL: name: urem16
; GEN64: CALL_Pseudo &__umodhi3
  %r = urem i16 %a, %b
  ret i16 %r
}
