; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --no-generate-mir --nocpp
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN64

; Test that 32-bit MUL/DIV/REM operations are legalized as libcalls on
; CPUs with the DW extension (word size >= 32).

define i32 @mul32(i32 %a, i32 %b) {
; GEN32-LABEL: name: mul32
; GEN32: CALL_Pseudo &__mulsi3
; GEN64-LABEL: name: mul32
; GEN64: CALL_Pseudo &__mulsi3
  %r = mul i32 %a, %b
  ret i32 %r
}

define i32 @sdiv32(i32 %a, i32 %b) {
; GEN32-LABEL: name: sdiv32
; GEN32: CALL_Pseudo &__divsi3
; GEN64-LABEL: name: sdiv32
; GEN64: CALL_Pseudo &__divsi3
  %r = sdiv i32 %a, %b
  ret i32 %r
}

define i32 @udiv32(i32 %a, i32 %b) {
; GEN32-LABEL: name: udiv32
; GEN32: CALL_Pseudo &__udivsi3
; GEN64-LABEL: name: udiv32
; GEN64: CALL_Pseudo &__udivsi3
  %r = udiv i32 %a, %b
  ret i32 %r
}

define i32 @srem32(i32 %a, i32 %b) {
; GEN32-LABEL: name: srem32
; GEN32: CALL_Pseudo &__modsi3
; GEN64-LABEL: name: srem32
; GEN64: CALL_Pseudo &__modsi3
  %r = srem i32 %a, %b
  ret i32 %r
}

define i32 @urem32(i32 %a, i32 %b) {
; GEN32-LABEL: name: urem32
; GEN32: CALL_Pseudo &__umodsi3
; GEN64-LABEL: name: urem32
; GEN64: CALL_Pseudo &__umodsi3
  %r = urem i32 %a, %b
  ret i32 %r
}
