; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s --check-prefixes=PTR16
; RUN: llc -march=etca -mcpu=generic -mattr=+ptr32,+32bit < %s | FileCheck %s --check-prefixes=PTR32
; RUN: llc -march=etca -mcpu=generic -mattr=+ptr64,+64bit < %s | FileCheck %s --check-prefixes=PTR64

; Test that G_CONSTANT / G_IMPLICIT_DEF / G_INTTOPTR / G_PTRTOINT with
; pointer type (p0) legalize correctly. This was a bug: the legalizer
; didn't mark p0 as legal for these operations, causing:
;   "LLVM ERROR: unable to legalize instruction: %0:_(p0) = G_CONSTANT i32 0"
; for constructs like `ret ptr null`.

; The IR uses default p:16 datalayout. -mattr overrides it to the correct
; size. Tests run with three pointer sizes: 16-bit (default), 32-bit,
; and 64-bit.

target datalayout = "e-m:e-p:16:16-i8:8-i16:16-i32:32-i64:32-f32:32-f64:32-a:0-n8:16:32-S16"
target triple = "etca-unknown-elf16"

; ---------------------------------------------------------------------------;
; ret ptr null  →  G_CONSTANT p0, 0
; ---------------------------------------------------------------------------;

; PTR16-LABEL: D_PopEvent:
; PTR16:       movz %r0, 0
; PTR16-NEXT:  jmpr %r7

; PTR32-LABEL: D_PopEvent:
; PTR32:       movz %r0d, 0
; PTR32-NEXT:  jmpr %r7

; PTR64-LABEL: D_PopEvent:
; PTR64:       movz %r0q, 0
; PTR64-NEXT:  jmpr %r7

define ptr @D_PopEvent() {
entry:
  ret ptr null
}

; ---------------------------------------------------------------------------;
; ret ptr inttoptr (i16 16 to ptr)  →  G_INTTOPTR
; ---------------------------------------------------------------------------;

; PTR16-LABEL: D_GetGlobal:
; PTR16:       movz %r0, 16
; PTR16-NEXT:  jmpr %r7

; PTR32-LABEL: D_GetGlobal:
; PTR32:       movz %r0, 16
; PTR32-NEXT:  jmpr %r7

; PTR64-LABEL: D_GetGlobal:
; PTR64:       movz %r0, 16
; PTR64-NEXT:  jmpr %r7

define ptr @D_GetGlobal() {
entry:
  ret ptr inttoptr (i16 16 to ptr)
}

; ---------------------------------------------------------------------------;
; ret ptr undef  →  G_IMPLICIT_DEF p0
; ---------------------------------------------------------------------------;

; PTR16-LABEL: D_UndefPtr:
; PTR16:       movz %r0, 0
; PTR16-NEXT:  jmpr %r7

; PTR32-LABEL: D_UndefPtr:
; PTR32:       movz %r0d, 0
; PTR32-NEXT:  jmpr %r7

; PTR64-LABEL: D_UndefPtr:
; PTR64:       movz %r0q, 0
; PTR64-NEXT:  jmpr %r7

define ptr @D_UndefPtr() {
entry:
  ret ptr undef
}

; ---------------------------------------------------------------------------;
; inttoptr + ptrtoint roundtrip  →  G_INTTOPTR + G_PTRTOINT (+ G_TRUNC)
;
; For 32-bit/64-bit modes, the G_INTTOPTR extends i16 to pointer width, then
; G_PTRTOINT produces a wider int, and G_TRUNC narrows back to i16.  The
; truncation emits movs (sign-extend semantics per ETCa spec).
; For 16-bit mode, all widths match so no truncation is needed.
; ---------------------------------------------------------------------------;

; PTR16-LABEL: D_NullToInt:
; PTR16:       movz %r0, 0
; PTR16-NEXT:  jmpr %r7

; PTR32-LABEL: D_NullToInt:
; PTR32:       movz %r0, 0
; PTR32:       movs %r0, %r0
; PTR32-NEXT:  jmpr %r7

; PTR64-LABEL: D_NullToInt:
; PTR64:       movz %r0, 0
; PTR64:       movs %r0, %r0
; PTR64-NEXT:  jmpr %r7

define i16 @D_NullToInt() {
entry:
  %p = inttoptr i16 0 to ptr
  %i = ptrtoint ptr %p to i16
  ret i16 %i
}
