; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --no-generate-mir --nocpp
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN64

; Test that 32-bit ASHR/LSHR operations are legalized as libcalls on
; CPUs with the DW extension (word size >= 32).

define i32 @ashr32(i32 %a, i32 %b) {
; GEN32-LABEL: name: ashr32
; GEN32: CALL_Pseudo &__ashrsi3
; GEN64-LABEL: name: ashr32
; GEN64: CALL_Pseudo &__ashrsi3
  %r = ashr i32 %a, %b
  ret i32 %r
}

define i32 @lshr32(i32 %a, i32 %b) {
; GEN32-LABEL: name: lshr32
; GEN32: CALL_Pseudo &__lshrsi3
; GEN64-LABEL: name: lshr32
; GEN64: CALL_Pseudo &__lshrsi3
  %r = lshr i32 %a, %b
  ret i32 %r
}

define i32 @ashr32_const(i32 %a) {
; GEN32-LABEL: name: ashr32_const
; GEN32: CALL_Pseudo &__ashrsi3
; GEN64-LABEL: name: ashr32_const
; GEN64: CALL_Pseudo &__ashrsi3
  %r = ashr i32 %a, 7
  ret i32 %r
}

define i32 @lshr32_const(i32 %a) {
; GEN32-LABEL: name: lshr32_const
; GEN32: CALL_Pseudo &__lshrsi3
; GEN64-LABEL: name: lshr32_const
; GEN64: CALL_Pseudo &__lshrsi3
  %r = lshr i32 %a, 3
  ret i32 %r
}
