; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=instruction-select < %s | FileCheck %s --check-prefix=GEN64

; Test that 64-bit ASHR/LSHR operations are legalized as libcalls on
; CPUs with the QW extension (word size >= 64).

define i64 @ashr64(i64 %a, i64 %b) {
  ; GEN64-LABEL: name: ashr64
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   $q1 = COPY [[COPY1]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashrdi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   $q0 = COPY [[COPY2]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = ashr i64 %a, %b
  ret i64 %r
}

define i64 @lshr64(i64 %a, i64 %b) {
  ; GEN64-LABEL: name: lshr64
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   $q1 = COPY [[COPY1]]
  ; GEN64-NEXT:   CALL_Pseudo &__lshrdi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   $q0 = COPY [[COPY2]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = lshr i64 %a, %b
  ret i64 %r
}

define i64 @ashr64_const(i64 %a) {
  ; GEN64-LABEL: name: ashr64_const
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZI64_:%[0-9]+]]:gpr64 = MOVZI64 15
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   $q1 = COPY [[MOVZI64_]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashrdi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   $q0 = COPY [[COPY1]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = ashr i64 %a, 15
  ret i64 %r
}

define i64 @lshr64_const(i64 %a) {
  ; GEN64-LABEL: name: lshr64_const
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZI64_:%[0-9]+]]:gpr64 = MOVZI64 4
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   $q1 = COPY [[MOVZI64_]]
  ; GEN64-NEXT:   CALL_Pseudo &__lshrdi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   $q0 = COPY [[COPY1]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = lshr i64 %a, 4
  ret i64 %r
}
