; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --no-generate-mir --nocpp
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+dw,+qw -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN64

; Test that 64-bit ASHR/LSHR operations are legalized as libcalls on
; CPUs with the QW extension (word size >= 64).

define i64 @ashr64(i64 %a, i64 %b) {
; GEN64-LABEL: name: ashr64
; GEN64: CALL_Pseudo &__ashrdi3
  %r = ashr i64 %a, %b
  ret i64 %r
}

define i64 @lshr64(i64 %a, i64 %b) {
; GEN64-LABEL: name: lshr64
; GEN64: CALL_Pseudo &__lshrdi3
  %r = lshr i64 %a, %b
  ret i64 %r
}

define i64 @ashr64_const(i64 %a) {
; GEN64-LABEL: name: ashr64_const
; GEN64: CALL_Pseudo &__ashrdi3
  %r = ashr i64 %a, 15
  ret i64 %r
}

define i64 @lshr64_const(i64 %a) {
; GEN64-LABEL: name: lshr64_const
; GEN64: CALL_Pseudo &__lshrdi3
  %r = lshr i64 %a, 4
  ret i64 %r
}
