; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=etca -mcpu=generic -stop-after=instruction-select < %s | FileCheck %s --check-prefix=GEN16
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -stop-after=instruction-select < %s | FileCheck %s --check-prefix=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=instruction-select < %s | FileCheck %s --check-prefix=GEN64

; Test that 16-bit ASHR/LSHR operations are legalized as libcalls on all CPUs.
; SHL is handled inline (not a libcall) — we test it here to confirm it stays.

define i16 @ashr16(i16 %a, i16 %b) {
  ; GEN16-LABEL: name: ashr16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r1, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r1
  ; GEN16-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   $r0 = COPY [[COPY]]
  ; GEN16-NEXT:   $r1 = COPY [[COPY1]]
  ; GEN16-NEXT:   CALL_Pseudo &__ashrhi3, csr_etca_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN16-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   $r0 = COPY [[COPY2]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: ashr16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $d1, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $d1
  ; GEN32-NEXT:   [[MOVZ32_1:%[0-9]+]]:gpr32 = MOVZ32 [[COPY2]]
  ; GEN32-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ32_1]]
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN32-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN32-NEXT:   CALL_Pseudo &__ashrhi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN32-NEXT:   [[COPY5:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY5]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: ashr16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   [[MOVZ64_1:%[0-9]+]]:gpr64 = MOVZ64 [[COPY2]]
  ; GEN64-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ64_1]]
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN64-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashrhi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN64-NEXT:   [[COPY5:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY5]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = ashr i16 %a, %b
  ret i16 %r
}

define i16 @lshr16(i16 %a, i16 %b) {
  ; GEN16-LABEL: name: lshr16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r1, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r1
  ; GEN16-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   $r0 = COPY [[COPY]]
  ; GEN16-NEXT:   $r1 = COPY [[COPY1]]
  ; GEN16-NEXT:   CALL_Pseudo &__lshrhi3, csr_etca_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN16-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   $r0 = COPY [[COPY2]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: lshr16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $d1, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $d1
  ; GEN32-NEXT:   [[MOVZ32_1:%[0-9]+]]:gpr32 = MOVZ32 [[COPY2]]
  ; GEN32-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ32_1]]
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN32-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN32-NEXT:   CALL_Pseudo &__lshrhi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN32-NEXT:   [[COPY5:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY5]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: lshr16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   [[MOVZ64_1:%[0-9]+]]:gpr64 = MOVZ64 [[COPY2]]
  ; GEN64-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ64_1]]
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN64-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN64-NEXT:   CALL_Pseudo &__lshrhi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN64-NEXT:   [[COPY5:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY5]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = lshr i16 %a, %b
  ret i16 %r
}

define i16 @shl16(i16 %a, i16 %b) {
  ; GEN16-LABEL: name: shl16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r1, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r1
  ; GEN16-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   $r0 = COPY [[COPY]]
  ; GEN16-NEXT:   $r1 = COPY [[COPY1]]
  ; GEN16-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN16-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   $r0 = COPY [[COPY2]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: shl16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $d1, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $d1
  ; GEN32-NEXT:   [[MOVZ32_1:%[0-9]+]]:gpr32 = MOVZ32 [[COPY2]]
  ; GEN32-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ32_1]]
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN32-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN32-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN32-NEXT:   [[COPY5:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY5]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   [[MOVZ64_1:%[0-9]+]]:gpr64 = MOVZ64 [[COPY2]]
  ; GEN64-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ64_1]]
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN64-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN64-NEXT:   [[COPY5:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY5]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i16 %a, %b
  ret i16 %r
}

define i16 @ashr16_const(i16 %a) {
  ; GEN16-LABEL: name: ashr16_const
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 3
  ; GEN16-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   $r0 = COPY [[COPY]]
  ; GEN16-NEXT:   $r1 = COPY [[MOVZI16_]]
  ; GEN16-NEXT:   CALL_Pseudo &__ashrhi3, csr_etca_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN16-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: ashr16_const
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 3
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN32-NEXT:   $r1 = COPY [[MOVZI16_]]
  ; GEN32-NEXT:   CALL_Pseudo &__ashrhi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY2]]
  ; GEN32-NEXT:   [[COPY3:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY3]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: ashr16_const
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 3
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN64-NEXT:   $r1 = COPY [[MOVZI16_]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashrhi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY2]]
  ; GEN64-NEXT:   [[COPY3:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY3]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = ashr i16 %a, 3
  ret i16 %r
}

define i16 @lshr16_const(i16 %a) {
  ; GEN16-LABEL: name: lshr16_const
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 5
  ; GEN16-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   $r0 = COPY [[COPY]]
  ; GEN16-NEXT:   $r1 = COPY [[MOVZI16_]]
  ; GEN16-NEXT:   CALL_Pseudo &__lshrhi3, csr_etca_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN16-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: lshr16_const
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 5
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN32-NEXT:   $r1 = COPY [[MOVZI16_]]
  ; GEN32-NEXT:   CALL_Pseudo &__lshrhi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY2]]
  ; GEN32-NEXT:   [[COPY3:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY3]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: lshr16_const
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 5
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN64-NEXT:   $r1 = COPY [[MOVZI16_]]
  ; GEN64-NEXT:   CALL_Pseudo &__lshrhi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY2]]
  ; GEN64-NEXT:   [[COPY3:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY3]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = lshr i16 %a, 5
  ret i16 %r
}
