; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --no-generate-mir --nocpp
; RUN: llc -march=etca -mcpu=generic -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN16
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=legalizer < %s | FileCheck %s --check-prefix=GEN64

; Test that 16-bit ASHR/LSHR operations are legalized as libcalls on all CPUs.
; SHL is handled inline (not a libcall) — we test it here to confirm it stays.

define i16 @ashr16(i16 %a, i16 %b) {
; GEN16-LABEL: name: ashr16
; GEN16: CALL_Pseudo &__ashrhi3
; GEN32-LABEL: name: ashr16
; GEN32: CALL_Pseudo &__ashrhi3
; GEN64-LABEL: name: ashr16
; GEN64: CALL_Pseudo &__ashrhi3
  %r = ashr i16 %a, %b
  ret i16 %r
}

define i16 @lshr16(i16 %a, i16 %b) {
; GEN16-LABEL: name: lshr16
; GEN16: CALL_Pseudo &__lshrhi3
; GEN32-LABEL: name: lshr16
; GEN32: CALL_Pseudo &__lshrhi3
; GEN64-LABEL: name: lshr16
; GEN64: CALL_Pseudo &__lshrhi3
  %r = lshr i16 %a, %b
  ret i16 %r
}

define i16 @shl16(i16 %a, i16 %b) {
; GEN16-LABEL: name: shl16
; GEN16-NOT: CALL_Pseudo
; GEN32-LABEL: name: shl16
; GEN32-NOT: CALL_Pseudo
; GEN64-LABEL: name: shl16
; GEN64-NOT: CALL_Pseudo
  %r = shl i16 %a, %b
  ret i16 %r
}

define i16 @ashr16_const(i16 %a) {
; GEN16-LABEL: name: ashr16_const
; GEN16: CALL_Pseudo &__ashrhi3
; GEN32-LABEL: name: ashr16_const
; GEN32: CALL_Pseudo &__ashrhi3
; GEN64-LABEL: name: ashr16_const
; GEN64: CALL_Pseudo &__ashrhi3
  %r = ashr i16 %a, 3
  ret i16 %r
}

define i16 @lshr16_const(i16 %a) {
; GEN16-LABEL: name: lshr16_const
; GEN16: CALL_Pseudo &__lshrhi3
; GEN32-LABEL: name: lshr16_const
; GEN32: CALL_Pseudo &__lshrhi3
; GEN64-LABEL: name: lshr16_const
; GEN64: CALL_Pseudo &__lshrhi3
  %r = lshr i16 %a, 5
  ret i16 %r
}
