; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32,+byte -stop-after=instruction-select < %s | FileCheck %s --check-prefixes=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+byte -stop-after=instruction-select < %s | FileCheck %s --check-prefixes=GEN64

; Test that 8-bit G_SHL is widened to i16 and then lowered to libcall __ashlhi3.

define signext i8 @shl_var_8(i8 signext %y, i8 signext %x) {
  ; GEN32-LABEL: name: shl_var_8
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $d1, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr8 = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $d1
  ; GEN32-NEXT:   [[MOVZ32_1:%[0-9]+]]:gpr32 = MOVZ32 [[COPY2]]
  ; GEN32-NEXT:   [[COPY3:%[0-9]+]]:gpr8 = COPY [[MOVZ32_1]]
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN32-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN32-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY4:%[0-9]+]]:gpr8 = COPY $r0
  ; GEN32-NEXT:   [[MOVS8_:%[0-9]+]]:gpr8 = MOVS8 [[COPY4]]
  ; GEN32-NEXT:   [[COPY5:%[0-9]+]]:gpr32 = COPY [[MOVS8_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY5]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_var_8
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr8 = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   [[MOVZ64_1:%[0-9]+]]:gpr64 = MOVZ64 [[COPY2]]
  ; GEN64-NEXT:   [[COPY3:%[0-9]+]]:gpr8 = COPY [[MOVZ64_1]]
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN64-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY4:%[0-9]+]]:gpr8 = COPY $r0
  ; GEN64-NEXT:   [[MOVS8_:%[0-9]+]]:gpr8 = MOVS8 [[COPY4]]
  ; GEN64-NEXT:   [[COPY5:%[0-9]+]]:gpr64 = COPY [[MOVS8_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY5]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i8 %y, %x
  ret i8 %r
}

define signext i8 @shl_zero_var_8(i8 signext %mask) {
  ; GEN32-LABEL: name: shl_zero_var_8
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[MOVZI8_:%[0-9]+]]:gpr8 = MOVZI8 0
  ; GEN32-NEXT:   [[MOVS8_:%[0-9]+]]:gpr8 = MOVS8 [[MOVZI8_]]
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY [[MOVS8_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_zero_var_8
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[MOVZI8_:%[0-9]+]]:gpr8 = MOVZI8 0
  ; GEN64-NEXT:   [[MOVS8_:%[0-9]+]]:gpr8 = MOVS8 [[MOVZI8_]]
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY [[MOVS8_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i8 0, %mask
  ret i8 %r
}

define signext i8 @shl_overflow_8(i8 signext %a) {
  ; GEN32-LABEL: name: shl_overflow_8
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[MOVZI8_:%[0-9]+]]:gpr8 = MOVZI8 0
  ; GEN32-NEXT:   [[MOVS8_:%[0-9]+]]:gpr8 = MOVS8 [[MOVZI8_]]
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY [[MOVS8_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_overflow_8
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[MOVZI8_:%[0-9]+]]:gpr8 = MOVZI8 0
  ; GEN64-NEXT:   [[MOVS8_:%[0-9]+]]:gpr8 = MOVS8 [[MOVZI8_]]
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY [[MOVS8_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i8 %a, 8
  ret i8 %r
}
