; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=instruction-select < %s | FileCheck %s --check-prefixes=GEN64

; Test that 64-bit G_SHL is lowered to libcall __ashldi3.

define i64 @shl_var_64(i64 %y, i64 %x) {
  ; GEN64-LABEL: name: shl_var_64
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   $q1 = COPY [[COPY1]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashldi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   $q0 = COPY [[COPY2]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i64 %y, %x
  ret i64 %r
}

define i64 @shl_zero_var_64(i64 %mask) {
  ; GEN64-LABEL: name: shl_zero_var_64
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[MOVZI64_:%[0-9]+]]:gpr64 = MOVZI64 0
  ; GEN64-NEXT:   $q0 = COPY [[MOVZI64_]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i64 0, %mask
  ret i64 %r
}

define i64 @shl_overflow_64(i64 %a) {
  ; GEN64-LABEL: name: shl_overflow_64
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[MOVZI64_:%[0-9]+]]:gpr64 = MOVZI64 0
  ; GEN64-NEXT:   $q0 = COPY [[MOVZI64_]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i64 %a, 64
  ret i64 %r
}
