; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -stop-after=legalizer < %s | FileCheck %s --check-prefixes=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=legalizer < %s | FileCheck %s --check-prefixes=GEN64

; Test that 32-bit G_SHL is lowered to libcall __ashlsi3.

define i32 @shl_var_32(i32 %y, i32 %x) {
  ; GEN32-LABEL: name: shl_var_32
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $d1, $r6, $r7, $r6
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $d0
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d1
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $d0 = COPY [[COPY]](s32)
  ; GEN32-NEXT:   $d1 = COPY [[COPY1]](s32)
  ; GEN32-NEXT:   CALL_Pseudo &__ashlsi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $d0, implicit $d1, implicit-def $d0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d0
  ; GEN32-NEXT:   $d0 = COPY [[COPY2]](s32)
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_var_32
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7, $r6
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $q0
  ; GEN64-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $q1
  ; GEN64-NEXT:   [[TRUNC1:%[0-9]+]]:_(s32) = G_TRUNC [[COPY1]](s64)
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[SEXT:%[0-9]+]]:_(s64) = G_SEXT [[TRUNC]](s32)
  ; GEN64-NEXT:   $q0 = COPY [[SEXT]](s64)
  ; GEN64-NEXT:   [[SEXT1:%[0-9]+]]:_(s64) = G_SEXT [[TRUNC1]](s32)
  ; GEN64-NEXT:   $q1 = COPY [[SEXT1]](s64)
  ; GEN64-NEXT:   CALL_Pseudo &__ashlsi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:_(s64) = COPY $q0
  ; GEN64-NEXT:   [[TRUNC2:%[0-9]+]]:_(s32) = G_TRUNC [[COPY2]](s64)
  ; GEN64-NEXT:   [[SEXT2:%[0-9]+]]:_(s64) = G_SEXT [[TRUNC2]](s32)
  ; GEN64-NEXT:   $q0 = COPY [[SEXT2]](s64)
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i32 %y, %x
  ret i32 %r
}

define i32 @shl_zero_var_32(i32 %mask) {
  ; GEN32-LABEL: name: shl_zero_var_32
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7, $r6
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $d0
  ; GEN32-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $d0 = COPY [[C]](s32)
  ; GEN32-NEXT:   $d1 = COPY [[COPY]](s32)
  ; GEN32-NEXT:   CALL_Pseudo &__ashlsi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $d0, implicit $d1, implicit-def $d0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d0
  ; GEN32-NEXT:   $d0 = COPY [[COPY1]](s32)
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_zero_var_32
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7, $r6
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $q0
  ; GEN64-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
  ; GEN64-NEXT:   $q0 = COPY [[C]](s64)
  ; GEN64-NEXT:   [[SEXT:%[0-9]+]]:_(s64) = G_SEXT [[TRUNC]](s32)
  ; GEN64-NEXT:   $q1 = COPY [[SEXT]](s64)
  ; GEN64-NEXT:   CALL_Pseudo &__ashlsi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $q0
  ; GEN64-NEXT:   [[TRUNC1:%[0-9]+]]:_(s32) = G_TRUNC [[COPY1]](s64)
  ; GEN64-NEXT:   [[SEXT1:%[0-9]+]]:_(s64) = G_SEXT [[TRUNC1]](s32)
  ; GEN64-NEXT:   $q0 = COPY [[SEXT1]](s64)
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i32 0, %mask
  ret i32 %r
}

define i32 @shl_overflow_32(i32 %a) {
  ; GEN32-LABEL: name: shl_overflow_32
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7, $r6
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $d0
  ; GEN32-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $d0 = COPY [[COPY]](s32)
  ; GEN32-NEXT:   $d1 = COPY [[C]](s32)
  ; GEN32-NEXT:   CALL_Pseudo &__ashlsi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $d0, implicit $d1, implicit-def $d0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d0
  ; GEN32-NEXT:   $d0 = COPY [[COPY1]](s32)
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_overflow_32
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7, $r6
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $q0
  ; GEN64-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[SEXT:%[0-9]+]]:_(s64) = G_SEXT [[TRUNC]](s32)
  ; GEN64-NEXT:   $q0 = COPY [[SEXT]](s64)
  ; GEN64-NEXT:   [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 32
  ; GEN64-NEXT:   $q1 = COPY [[C]](s64)
  ; GEN64-NEXT:   CALL_Pseudo &__ashlsi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $q0, implicit $q1, implicit-def $q0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:_(s64) = COPY $q0
  ; GEN64-NEXT:   [[TRUNC1:%[0-9]+]]:_(s32) = G_TRUNC [[COPY1]](s64)
  ; GEN64-NEXT:   [[SEXT1:%[0-9]+]]:_(s64) = G_SEXT [[TRUNC1]](s32)
  ; GEN64-NEXT:   $q0 = COPY [[SEXT1]](s64)
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i32 %a, 32
  ret i32 %r
}
