; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=etca -mcpu=generic -stop-after=instruction-select < %s | FileCheck %s --check-prefixes=GEN16
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -stop-after=instruction-select < %s | FileCheck %s --check-prefixes=GEN32
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -stop-after=instruction-select < %s | FileCheck %s --check-prefixes=GEN64

; Test that G_SHL is lowered to a libcall (__ashlhi3 for i16, __ashlsi3 for
; i32, __ashldi3 for i64) by the legalizer.
; Also verify constant-zero left operand and overflow cases.

define i16 @shl_var_16(i16 %y, i16 %x) {
  ; GEN16-LABEL: name: shl_var_16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r1, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $r1
  ; GEN16-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   $r0 = COPY [[COPY]]
  ; GEN16-NEXT:   $r1 = COPY [[COPY1]]
  ; GEN16-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN16-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN16-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   $r0 = COPY [[COPY2]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: shl_var_16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $d1, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $d1
  ; GEN32-NEXT:   [[MOVZ32_1:%[0-9]+]]:gpr32 = MOVZ32 [[COPY2]]
  ; GEN32-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ32_1]]
  ; GEN32-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN32-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN32-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_gpr64_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN32-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN32-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN32-NEXT:   [[COPY5:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY5]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_var_16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $q1, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $q1
  ; GEN64-NEXT:   [[MOVZ64_1:%[0-9]+]]:gpr64 = MOVZ64 [[COPY2]]
  ; GEN64-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY [[MOVZ64_1]]
  ; GEN64-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   $r0 = COPY [[COPY1]]
  ; GEN64-NEXT:   $r1 = COPY [[COPY3]]
  ; GEN64-NEXT:   CALL_Pseudo &__ashlhi3, csr_etca_preserveall_gpr32_regmask, implicit-def $r7, implicit $r0, implicit $r1, implicit-def $r0
  ; GEN64-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $r6, implicit $r6
  ; GEN64-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $r0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[COPY4]]
  ; GEN64-NEXT:   [[COPY5:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY5]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i16 %y, %x
  ret i16 %r
}

define i16 @shl_zero_var_16(i16 %mask) {
  ; GEN16-LABEL: name: shl_zero_var_16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN16-NEXT:   $r0 = COPY [[MOVZI16_]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: shl_zero_var_16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZI16_]]
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_zero_var_16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZI16_]]
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i16 0, %mask
  ret i16 %r
}

define i16 @shl_by_zero_16(i16 %a) {
  ; GEN16-LABEL: name: shl_by_zero_16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $r0
  ; GEN16-NEXT:   [[MOVZ16_:%[0-9]+]]:gpr = MOVZ16 [[COPY]]
  ; GEN16-NEXT:   $r0 = COPY [[MOVZ16_]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: shl_by_zero_16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY $d0
  ; GEN32-NEXT:   [[MOVZ32_:%[0-9]+]]:gpr32 = MOVZ32 [[COPY]]
  ; GEN32-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ32_]]
  ; GEN32-NEXT:   [[MOVZ16_:%[0-9]+]]:gpr = MOVZ16 [[COPY1]]
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZ16_]]
  ; GEN32-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY2]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_by_zero_16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $q0
  ; GEN64-NEXT:   [[MOVZ64_:%[0-9]+]]:gpr64 = MOVZ64 [[COPY]]
  ; GEN64-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY [[MOVZ64_]]
  ; GEN64-NEXT:   [[MOVZ16_:%[0-9]+]]:gpr = MOVZ16 [[COPY1]]
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZ16_]]
  ; GEN64-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY2]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i16 %a, 0
  ret i16 %r
}

define i16 @shl_overflow_16(i16 %a) {
  ; GEN16-LABEL: name: shl_overflow_16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN16-NEXT:   $r0 = COPY [[MOVZI16_]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: shl_overflow_16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZI16_]]
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_overflow_16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZI16_]]
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i16 %a, 16
  ret i16 %r
}

define i16 @shl_neg_16(i16 %a) {
  ; GEN16-LABEL: name: shl_neg_16
  ; GEN16: bb.1 (%ir-block.0):
  ; GEN16-NEXT:   liveins: $r0, $r6, $r7
  ; GEN16-NEXT: {{  $}}
  ; GEN16-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN16-NEXT:   $r0 = COPY [[MOVZI16_]]
  ; GEN16-NEXT:   RET_Pseudo implicit $r0
  ;
  ; GEN32-LABEL: name: shl_neg_16
  ; GEN32: bb.1 (%ir-block.0):
  ; GEN32-NEXT:   liveins: $d0, $r6, $r7
  ; GEN32-NEXT: {{  $}}
  ; GEN32-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN32-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZI16_]]
  ; GEN32-NEXT:   [[COPY:%[0-9]+]]:gpr32 = COPY [[MOVS16_]]
  ; GEN32-NEXT:   $d0 = COPY [[COPY]]
  ; GEN32-NEXT:   RET_Pseudo implicit $d0
  ;
  ; GEN64-LABEL: name: shl_neg_16
  ; GEN64: bb.1 (%ir-block.0):
  ; GEN64-NEXT:   liveins: $q0, $r6, $r7
  ; GEN64-NEXT: {{  $}}
  ; GEN64-NEXT:   [[MOVZI16_:%[0-9]+]]:gpr = MOVZI16 0
  ; GEN64-NEXT:   [[MOVS16_:%[0-9]+]]:gpr = MOVS16 [[MOVZI16_]]
  ; GEN64-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY [[MOVS16_]]
  ; GEN64-NEXT:   $q0 = COPY [[COPY]]
  ; GEN64-NEXT:   RET_Pseudo implicit $q0
  %r = shl i16 %a, -1
  ret i16 %r
}
