; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; Test that spilling after the last instruction in a fallthrough block
; (where I == MBB.end()) does not crash in storeRegToStackSlot/loadRegFromStackSlot.
;
; This regression was triggered when InlineSpiller called std::next(MI) on the
; last non-terminator instruction of a block that falls through (no terminator).
; std::next(MI) == MBB.end(), and storeRegToStackSlot/loadRegFromStackSlot
; dereference the iterator for DebugLoc, hitting a sentinel assertion.
;
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -O1 < %s 2>&1 | FileCheck %s --check-prefix=ETCA
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -O1 < %s 2>&1 | FileCheck %s --check-prefix=ETCA64

target datalayout = "e-m:e-p:32:32-i8:8-i16:16-i32:32-i64:32-f32:32-f64:32-a:0-n8:16:32-S32"
target triple = "etca-unknown-elf32"

@g0 = external global i32
@g1 = external global i32
@g2 = external global i32
@g3 = external global i32
@g4 = external global i32
@g5 = external global i32
@g6 = external global i32

; Use enough live virtual registers (7+ for 32-bit, where 5 are allocatable)
; in a loop structure with a fallthrough edge from entry to loop.
; The entry block has defs that end without a terminator (fallthrough).
; With >5 vregs live across the loop, the register allocator must spill.
; ETCA-LABEL: fallthrough_spill:
; ETCA:       push %r5
; ETCA:       push %r3
; ETCA:       push %r4
; ETCA:       sub %r6
; ETCA:       store
; ETCA:       store
; ETCA:       jmpr %r7

; ETCA64-LABEL: fallthrough_spill:
; ETCA64:       push %r5
; ETCA64:       push %r3
; ETCA64:       push %r4
; ETCA64:       sub %r6
; ETCA64:       store
; ETCA64:       store
; ETCA64:       jmpr %r7
define void @fallthrough_spill() {
entry:
  %a0 = load volatile i32, ptr @g0
  %a1 = load volatile i32, ptr @g1
  %a2 = load volatile i32, ptr @g2
  %a3 = load volatile i32, ptr @g3
  %a4 = load volatile i32, ptr @g4
  %a5 = load volatile i32, ptr @g5
  %a6 = load volatile i32, ptr @g6
  br label %loop

loop:
  %b0 = add i32 %a0, %a1
  %b1 = add i32 %b0, %a2
  %b2 = add i32 %b1, %a3
  %b3 = add i32 %b2, %a4
  %b4 = add i32 %b3, %a5
  %b5 = add i32 %b4, %a6
  store volatile i32 %b5, ptr @g0
  %cond = icmp eq i32 %b0, 0
  br i1 %cond, label %exit, label %loop

exit:
  ret void
}
