;; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -march=etca -mcpu=generic < %s | FileCheck %s --check-prefixes=GN
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 < %s | FileCheck %s --check-prefixes=EW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 < %s | FileCheck %s --check-prefixes=QW

;; ===========================================================================
;; ETCA Stack Argument Codegen Tests
;;
;; Tests that calls with 5+ arguments (excess args passed on stack) work
;; correctly for all word sizes.  After the fix for issues #1 and #2:
;;
;;   Issue #1: lowerCall hardcoded STORE16/ADDI16 — fixed to use the correct
;;             STORE{16,32,64} matching the argument's bit width.
;;
;;   Issue #3: lowerCall manually emitted SUBI16/ADDI16 for stack adjustment
;;             — fixed to use ADJCALLSTACKDOWN/ADJCALLSTACKUP markers which
;;             are expanded by eliminateCallFramePseudoInstr into width-aware
;;             SUBI/ADDI with proper PEI integration.
;;
;; Key invariants verified:
;;   1. Stack arg allocation uses sub %r6, N / add %r6, N around calls
;;      (from ADJCALLSTACKDOWN/ADJCALLSTACKUP expansion)
;;   2. Stack allocation size = NumStackArgs * RegBytes
;;   3. Store width matches argument type (STORE16/STORE32/STORE64)
;;   4. All CPU models (16-bit, 32-bit, 64-bit word) produce valid output
;;
;; Calling convention:
;;   - First 4 arguments in r0-r3 (or d0-d3 / q0-q3 for wider types)
;;   - Remaining arguments on the stack, naturally aligned
;; ===========================================================================

;; ---------------------------------------------------------------------------
;; 5-arg call (16-bit): 4 register args + 1 stack arg
;; ---------------------------------------------------------------------------

declare i16 @sum5_16(i16, i16, i16, i16, i16)

define i16 @caller_5args_16() {
; GN-LABEL: caller_5args_16:
; GN:       sub %r6, 2
; GN:       store
; GN:       call sum5_16
; GN:       add %r6, 2
;
; EW-LABEL: caller_5args_16:
; EW:       sub %r6, 4
; EW:       store
; EW:       call sum5_16
; EW:       add %r6, 4
;
; QW-LABEL: caller_5args_16:
; QW:       sub %r6, 8
; QW:       store
; QW:       call sum5_16
; QW:       add %r6, 8
  %r = call i16 @sum5_16(i16 1, i16 2, i16 3, i16 4, i16 5)
  ret i16 %r
}

;; ---------------------------------------------------------------------------
;; 6-arg call (16-bit): 4 register + 2 stack args
;; ---------------------------------------------------------------------------

declare i16 @sum6_16(i16, i16, i16, i16, i16, i16)

define i16 @caller_6args_16() {
; GN-LABEL: caller_6args_16:
; GN:       sub %r6, 4
; GN:       call sum6_16
; GN:       add %r6, 4
;
; EW-LABEL: caller_6args_16:
; EW:       sub %r6, 8
; EW:       call sum6_16
; EW:       add %r6, 8
;
; QW-LABEL: caller_6args_16:
; QW:       sub %r6, 16
; QW:       call sum6_16
; QW:       add %r6, 16
  %r = call i16 @sum6_16(i16 1, i16 2, i16 3, i16 4, i16 5, i16 6)
  ret i16 %r
}

;; ---------------------------------------------------------------------------
;; 10-arg call (16-bit): stress test with 6 stack args
;; ---------------------------------------------------------------------------

declare i16 @sum10_16(i16, i16, i16, i16, i16, i16, i16, i16, i16, i16)

define i16 @caller_10args_16() {
; GN-LABEL: caller_10args_16:
; GN:       sub %r6, 12
; GN:       call sum10_16
; GN:       add %r6, 12
;
; EW-LABEL: caller_10args_16:
; EW:       sub %r6, 24
; EW:       call sum10_16
; EW:       add %r6, 24
;
; QW-LABEL: caller_10args_16:
; QW:       sub %r6,
; QW:       call sum10_16
; QW:       add %r6,
  %r = call i16 @sum10_16(i16 1, i16 2, i16 3, i16 4, i16 5, i16 6, i16 7, i16 8, i16 9, i16 10)
  ret i16 %r
}

;; ---------------------------------------------------------------------------
;; 5-arg call (32-bit): verify STORE32 is used for i32 stack arg
;;                      (not hardcoded STORE16)
;; ---------------------------------------------------------------------------

declare i32 @sum5_32(i32, i32, i32, i32, i32)

define i32 @caller_5args_32() {
; EW-LABEL: caller_5args_32:
; EW:       store %r{{[0-9]+}}d, %r6
; EW:       call sum5_32
;
; QW-LABEL: caller_5args_32:
; QW:       store %r{{[0-9]+}}d, %r6
; QW:       call sum5_32
  %r = call i32 @sum5_32(i32 1, i32 2, i32 3, i32 4, i32 5)
  ret i32 %r
}

;; ---------------------------------------------------------------------------
;; 5-arg call (64-bit): verify STORE64 is used for i64 stack arg
;; ---------------------------------------------------------------------------

declare i64 @sum5_64(i64, i64, i64, i64, i64)

define i64 @caller_5args_64() {
; QW-LABEL: caller_5args_64:
; QW:       store %r{{[0-9]+}}q, %r6
; QW:       call sum5_64
  %r = call i64 @sum5_64(i64 1, i64 2, i64 3, i64 4, i64 5)
  ret i64 %r
}
