; NOTE: Assertions have been autogenerated by running clang -O1 -emit-llvm
; on the C strcpy source, then llc -O1 with -mcpu= for each CPU model.
;
; This test verifies that clang -O1 compilation of a strcpy-style byte-per-byte
; loop produces correct assembly on all 5 ETCA CPU models.
;
; The key difference from strcpy-opt1.ll is that this test uses the streamlined
; LLVM IR that clang -O1 actually generates (phi-node-based loop with GEP for
; pointer increment), rather than the explicit alloca/load/store pointer pattern
; used in strcpy-opt1.ll (which mimics -O0).
;
; On generic (16-bit word, 16-bit ptr), the 16-bit GEP offset is legal so the
; legalizer keeps the loop as-is. The allocator spills pointers and uses an
; index variable due to register pressure.
;
; On 32/64-bit ptr targets (etca32, etca32p64, etca64p32, etca64), the
; legalizer accepts the 16-bit GEP offset (legal for all targets), and the
; post-RA optimiser produces a tight 4-instruction loop body with direct
; pointer increments.

; RUN: llc -march=etca -mcpu=generic -O1 < %s | FileCheck %s --check-prefix=GEN
; RUN: llc -march=etca -mcpu=etca32 -O1 < %s | FileCheck %s --check-prefix=DW
; RUN: llc -march=etca -mcpu=etca64 -O1 < %s | FileCheck %s --check-prefix=QW
; RUN: llc -march=etca -mcpu=etca32p64 -O1 < %s | FileCheck %s --check-prefix=QW
; RUN: llc -march=etca -mcpu=etca64p32 -O1 < %s | FileCheck %s --check-prefix=DW

;; ===========================================================================
;; strcpy at -O1 — phi-node loop with GEP-based pointer increment
;;
;; The function copies bytes from src to dest until the null terminator is
;; encountered, then returns the original dest pointer.
;;
;; clang -O1 generates a tight loop with two phi nodes (src_ptr, dst_ptr),
;; byte load/store, GEP increment, comparison, and conditional branch.
;; ===========================================================================

define ptr @mystrcpy(ptr %dest, ptr %src) {
; GEN-LABEL: mystrcpy:
; GEN:       push %r5
; GEN:       movz %r5, %r6
; GEN:       sub %r6, 6
;; Prologue: spill callee-saves and arguments (using scratch regs)
; GEN:       store %r3, %r{{[0-9]+}}
; GEN:       store %r4, %r{{[0-9]+}}
; GEN:       store %r0, %r{{[0-9]+}}
; GEN:       movz %r2h, 0
; GEN:       movz %r{{[0-9]+}}, 1
; GEN:       movz %r{{[0-9]+}}, 0
;; Loop body: dest + index, load byte from src, store to dest, inc
; GEN:       add %r{{[0-9]+}}, %r{{[0-9]+}}
; GEN:       load %r{{[0-9]+}}h
; GEN:       store %r{{[0-9]+}}h
;; Check for null terminator
; GEN:       cmp %r{{[0-9]+}}, %r2
; GEN:       beq
; GEN:       br
;; Return: reload original dest ptr and return
; GEN:       movz %r0, %r5
; GEN:       load %r0, %r0
; GEN:       jmpr %r7
;
;; --- 32-bit pointer CPUs (etca32, etca64p32) ---
;; Tight loop with dword-sized increment
; DW-LABEL: mystrcpy:
; DW:       push %r5
; DW:       movz %r5, %r6
; DW:       sub %r6,
; DW:       movz %r{{[0-9]+}}, %r5
; DW:       store %r3, %r{{[0-9]+}}
; DW:       movz %r{{[0-9]+}}, %r5
; DW:       store %r4, %r{{[0-9]+}}
; DW:       movz %r2h, 0
; DW:       movz %r{{[0-9]+}}d, 1
;; Loop: load byte from src, store to dest, increment both pointers
; DW:       load %r{{[0-9]+}}h, %r{{[0-9]+}}h
; DW:       store %r{{[0-9]+}}h, %r{{[0-9]+}}h
; DW:       add %r{{[0-9]+}}, %r{{[0-9]+}}d
; DW:       add %r{{[0-9]+}}, %r{{[0-9]+}}d
; DW:       cmp %r{{[0-9]+}}, %r2
; DW-NEXT:  beq
; DW-NEXT:  br
;; Return
; DW:       jmpr %r7
;
;; --- 64-bit pointer CPUs (etca64, etca32p64) ---
;; Tight loop with qword-sized increment
; QW-LABEL: mystrcpy:
; QW:       push %r5
; QW:       movz %r5, %r6
; QW:       sub %r6,
; QW:       movz %r{{[0-9]+}}, %r5
; QW:       store %r3, %r{{[0-9]+}}
; QW:       movz %r{{[0-9]+}}, %r5
; QW:       store %r4, %r{{[0-9]+}}
; QW:       movz %r2h, 0
; QW:       movz %r{{[0-9]+}}q, 1
;; Loop: load byte from src, store to dest, increment both pointers
; QW:       load %r{{[0-9]+}}h, %r{{[0-9]+}}h
; QW:       store %r{{[0-9]+}}h, %r{{[0-9]+}}h
; QW:       add %r{{[0-9]+}}, %r{{[0-9]+}}q
; QW:       add %r{{[0-9]+}}, %r{{[0-9]+}}q
; QW:       cmp %r{{[0-9]+}}, %r2
; QW-NEXT:  beq
; QW-NEXT:  br
;; Return
; QW:       jmpr %r7

entry:
  br label %loop

loop:
  %src_phi = phi ptr [ %src, %entry ], [ %inc_src, %loop ]
  %dst_phi = phi ptr [ %dest, %entry ], [ %inc_dst, %loop ]
  %byte = load i8, ptr %src_phi
  store i8 %byte, ptr %dst_phi
  %inc_src = getelementptr inbounds nuw i8, ptr %src_phi, i16 1
  %inc_dst = getelementptr inbounds nuw i8, ptr %dst_phi, i16 1
  %is_zero = icmp eq i8 %byte, 0
  br i1 %is_zero, label %return, label %loop

return:
  ret ptr %dest
}
