; NOTE: Assertions have been autogenerated by running clang -O1 -emit-llvm
; on the C strcpy source, then llc -O1 with -mcpu= for each CPU model.
;
; This test verifies that clang -O1 compilation of a strcpy-style byte-per-byte
; loop produces correct assembly on all 5 ETCA CPU models.
;
; The key difference from strcpy-opt1.ll is that this test uses the streamlined
; LLVM IR that clang -O1 actually generates (phi-node-based loop with GEP for
; pointer increment), rather than the explicit alloca/load/store pointer pattern
; used in strcpy-opt1.ll (which mimics -O0).
;
; On generic (16-bit word, 16-bit ptr), the 16-bit GEP offset is legal so the
; legalizer keeps the loop as-is. The allocator spills pointers and uses an
; index variable due to register pressure.
;
; On 32/64-bit ptr targets (etca32, etca32p64, etca64p32, etca64), the
; legalizer accepts the 16-bit GEP offset (legal for all targets), and the
; post-RA optimiser produces a tight 4-instruction loop body with direct
; pointer increments.

; RUN: llc -march=etca -mcpu=generic -O1 < %s | FileCheck %s --check-prefix=GEN
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32,+dw -O1 < %s | FileCheck %s --check-prefix=DW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64,+dw,+qw -O1 < %s | FileCheck %s --check-prefix=QW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32,+dw,+qw -O1 < %s | FileCheck %s --check-prefix=QW

;; ===========================================================================
;; strcpy at -O1 — phi-node loop with GEP-based pointer increment
;;
;; The function copies bytes from src to dest until the null terminator is
;; encountered, then returns the original dest pointer.
;;
;; clang -O1 generates a tight loop with two phi nodes (src_ptr, dst_ptr),
;; byte load/store, GEP increment, comparison, and conditional branch.
;; ===========================================================================

define ptr @mystrcpy(ptr %dest, ptr %src) {
; GEN-LABEL: mystrcpy:
; GEN:       push %r5
; GEN:       movz %r5, %r6
; GEN:       push %r3
; GEN:       push %r4
; GEN:       movz %r2h, 0
; GEN:       movz %r{{[0-9]+}}, 0
;; Loop body: index-based load byte from src, store to dest, inc
; GEN:       add %r3, %r7
; GEN:       add %r4, %r7
; GEN:       load %r3h, %r3h
; GEN:       store %r3h, %r4h
; GEN:       add %r7, 1
;; Check for null terminator
; GEN:       cmp %r{{[0-9]+}}{{h?}}, %r{{[0-9]+}}{{h?}}
; GEN:       beq
; GEN:       br
;; Return: r0 (dest) still holds original value, no reload needed
; GEN:       jmpr %r7
;
;; --- 32-bit pointer CPUs (etca32, etca64p32) ---
;; Uses 32-bit index register (r7d) for pointer increments.
; DW-LABEL: mystrcpy:
; DW:       push %r5
; DW:       movz %r5, %r6
; DW:       push %r3
; DW:       push %r4
; DW:       movz %r2h, 0
; DW:       movz %r7d, 0
;; Loop: load byte from src, store to dest, increment index
; DW:       movz %r3{{[dq]?}}, %r1{{[dq]?}}
; DW:       add %r3{{[dq]?}}, %r7d
; DW:       movz %r4{{[dq]?}}, %r0{{[dq]?}}
; DW:       add %r4{{[dq]?}}, %r7d
; DW:       load %r3{{[dqh]?}}, %r3{{[dhq]}}
; DW:       store %r3{{[dqh]?}}, %r4{{[dhq]}}
; DW:       add %r7d, 1
; DW:       cmp %r3h, %r2h
; DW-NEXT:  beq
; DW-NEXT:  br
;; Return: restore stack, pop, jmpr
; DW:       jmpr %r7
;
;; --- 64-bit pointer CPUs (etca64, etca32p64) ---
;; Uses 64-bit index register (r7q) for pointer increments.
; QW-LABEL: mystrcpy:
; QW:       push %r5
; QW:       movz %r5, %r6
; QW:       push %r3
; QW:       push %r4
; QW:       movz %r2h, 0
; QW:       movz %r7{{[dq]}}, 0
;; Loop: load byte from src, store to dest, increment index
; QW:       movz %r3{{[dq]?}}, %r1{{[dq]?}}
; QW:       add %r3{{[dq]?}}, %r7{{[dq]}}
; QW:       movz %r4{{[dq]?}}, %r0{{[dq]?}}
; QW:       add %r4{{[dq]?}}, %r7{{[dq]}}
; QW:       load %r3{{[dqh]?}}, %r3{{[dhq]}}
; QW:       store %r3{{[dqh]?}}, %r4{{[dhq]}}
; QW:       add %r7{{[dq]}}, 1
; QW:       cmp %r3h, %r2h
; QW-NEXT:  beq
; QW-NEXT:  br
;; Return
; QW:       jmpr %r7

entry:
  br label %loop

loop:
  %src_phi = phi ptr [ %src, %entry ], [ %inc_src, %loop ]
  %dst_phi = phi ptr [ %dest, %entry ], [ %inc_dst, %loop ]
  %byte = load i8, ptr %src_phi
  store i8 %byte, ptr %dst_phi
  %inc_src = getelementptr inbounds nuw i8, ptr %src_phi, i16 1
  %inc_dst = getelementptr inbounds nuw i8, ptr %dst_phi, i16 1
  %is_zero = icmp eq i8 %byte, 0
  br i1 %is_zero, label %return, label %loop

return:
  ret ptr %dest
}
