; NOTE: Assertions have been autogenerated by running clang -O1 -emit-llvm
; on the C strcpy source, then llc -O1 with -mcpu=generic and -mattr= for
; each width combination.
;
; This test verifies that clang -O1 compilation of a strcpy-style byte-per-byte
; loop produces correct assembly on all ETCA width/pointer combinations.
;
; R7 (ln) is reserved as a dedicated scratch register for frame index
; elimination.  The loop spills the dest pointer to stack and uses R3 as
; the index register.

; RUN: llc -march=etca -mcpu=generic -O1 < %s | FileCheck %s --check-prefix=GEN
; RUN: llc -march=etca -mcpu=generic -mattr=+32bit,+ptr32 -O1 < %s | FileCheck %s --check-prefix=DW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr64 -O1 < %s | FileCheck %s --check-prefix=QW
; RUN: llc -march=etca -mcpu=generic -mattr=+64bit,+ptr32 -O1 < %s | FileCheck %s --check-prefix=P64

define ptr @mystrcpy(ptr %dest, ptr %src) {
; GEN-LABEL: mystrcpy:
; GEN:       push %r5
; GEN:       movz %r5, %r6
; GEN:       push %r3
; GEN:       push %r4
; GEN:       sub %r6, 2
; GEN:       movz %r2h, 0
; GEN:       movz %r3, 0
;; Loop: load byte, store byte, increment index
; GEN:       .LBB0_1:
; Skip the prologue code before the loop, then match load byte + store byte
; GEN:       load %r4h, %r4h
; GEN:       store %r4h,
; GEN:       add %r3, 1
; GEN:       cmp %r4h, %r2h
; GEN-NEXT:  beq
; GEN-NEXT:  br
; GEN:       jmpr %r7
;
; DW-LABEL: mystrcpy:
; DW:       push %r5
; DW:       movz %r5, %r6
; DW:       push %r3
; DW:       push %r4
; DW:       sub %r6, 4
; DW:       movz %r7d, %r5
; DW:       add %r7d, -4
; DW:       store %r0d, %r7d
; DW:       movz %r2h, 0
; DW:       movz %r3d, 0
;; Loop
; DW:       movz %r4d, %r1d
; DW:       add %r4d, %r3d
; DW:       load %r4, %r4d
; DW:       store %r4, %r0d
; DW:       add %r3d, 1
; DW:       cmp %r4h, %r2h
; DW-NEXT:  beq
; DW-NEXT:  br
; DW:       jmpr %r7
;
; QW-LABEL: mystrcpy:
; QW:       push %r5
; QW:       movz %r5, %r6
; QW:       push %r3
; QW:       push %r4
; QW:       sub %r6, 8
; QW:       movz %r7q, %r5
; QW:       add %r7q, -8
; QW:       store %r0q, %r7q
; QW:       movz %r2h, 0
; QW:       movz %r3q, 0
;; Loop
; QW:       movz %r4q, %r1q
; QW:       add %r4q, %r3q
; QW:       load %r4, %r4q
; QW:       store %r4, %r0q
; QW:       add %r3q, 1
; QW:       cmp %r4h, %r2h
; QW-NEXT:  beq
; QW-NEXT:  br
; QW:       jmpr %r7
;
; P64-LABEL: mystrcpy:
; P64:       push %r5
; P64:       movz %r5, %r6
; P64:       push %r3
; P64:       push %r4
; P64:       sub %r6, 8
; P64:       movz %r7d, %r5
; P64:       add %r7d, -4
; P64:       store %r0d, %r7d
; P64:       movz %r2h, 0
; P64:       movz %r3d, 0
;; Loop
; P64:       movz %r4d, %r1d
; P64:       add %r4d, %r3d
; P64:       load %r4, %r4d
; P64:       store %r4, %r0d
; P64:       add %r3d, 1
; P64:       cmp %r4h, %r2h
; P64-NEXT:  beq
; P64-NEXT:  br
; P64:       jmpr %r7

entry:
  br label %loop

loop:
  %src_phi = phi ptr [ %src, %entry ], [ %inc_src, %loop ]
  %dst_phi = phi ptr [ %dest, %entry ], [ %inc_dst, %loop ]
  %byte = load i8, ptr %src_phi
  store i8 %byte, ptr %dst_phi
  %inc_src = getelementptr inbounds nuw i8, ptr %src_phi, i16 1
  %inc_dst = getelementptr inbounds nuw i8, ptr %dst_phi, i16 1
  %is_zero = icmp eq i8 %byte, 0
  br i1 %is_zero, label %return, label %loop

return:
  ret ptr %dest
}
